grafana:
    adminPassword: ENC[AES256_GCM,data:9/CnhrsS33UEEDY=,iv:EAnG2gfYF0iaiyDDBFKRr/UlRUFFfyMDDtavLNOLvxc=,tag:P/9wDFuDYsfh3ea7J/feog==,type:str]
prometheus-snmp-exporter:
    snmp:
        community: ENC[AES256_GCM,data:0ONPaawhOw==,iv:gZN+NjK0zX6BbVRzdi8Ob2HzB4QzUWhnZkqDU0maIyc=,tag:U2UsABZrdIFJnxj3OBsh9A==,type:str]
prometheus-pve-exporter:
    pveConfig:
        cluster_dev:
            user: ENC[AES256_GCM,data:QUot0M7m3n7lmA==,iv:8hHtcg2mEbDR3N0jfwGAPyTfYGwY7ZMexntn+v0Qzu4=,tag:XP/WKV90jpgNy6lEXQZaGQ==,type:str]
            token_name: ENC[AES256_GCM,data:sBW75/80,iv:QQppUwwSqvJ4cY9PHdWVAzuqc0k0BsS4Q0hG4DeVbJ0=,tag:1BfwBfOLYX3a1ad85HGXSw==,type:str]
            token_value: ENC[AES256_GCM,data:Kpg6zsjSMoIEsOO2JHHwb1BPtJfNt3za9K/vXRb96oCEp1yz,iv:sYgJvRMDGFinE3dBWX2WPZmrrYHM0tUJ4n7GqJliGR0=,tag:c85ZBtY6Jtu6c6BRaVbuow==,type:str]
        cluster_prd:
            user: ENC[AES256_GCM,data:rxjFWl97m5Gf8Q==,iv:Cz9EEDoqz+u6lUZbBxFVOuTPRPlJw8xddcTMg0k1fPg=,tag:S2RHipxuVzSVEIUGPINDVw==,type:str]
            token_name: ENC[AES256_GCM,data:N9SJsP+h,iv:cKW8Yis9aTWe2tL86EwzpOqRA2u2dsyeMjwtuvzrhOY=,tag:j8xWqDrKnaQV1sO7XYnAcw==,type:str]
            token_value: ENC[AES256_GCM,data:RmAl/2EWXVJSYpma3TtCZObuvhmZEhkqZR2gj2Hw+u5CagvH,iv:Mu9GLolKsMwaN4mqViIDyw2iM/a96lgcfMvKc1aLPDQ=,tag:nsx0gEbwuGwtUKNM/ib6YQ==,type:str]
        cluster_prd2:
            user: ENC[AES256_GCM,data:BZUKIDdu61Qn8g==,iv:IVfPtdideMzRaJXGhsF9D8Tkri0pyLk5UT+h7+E/oP8=,tag:R0mj3e0CCKALR45O9NTJ+g==,type:str]
            token_name: ENC[AES256_GCM,data:qIYI43QO,iv:YRKwc42zpZd5t7RzbzRbnOgb73xe6qxxYQsdjcM1IzU=,tag:hA9iJ9AEo2XSqhdwiIwbRg==,type:str]
            token_value: ENC[AES256_GCM,data:8+TFew/VT7EZAJ+2iCY5FePqUjDv7LpyWUcYrKG5VkYaJXzW,iv:ALAgPVtXnNRiqqHgMuxfsMQujbsIKaAEPQ+RErDyMkA=,tag:xnotL/mSHEW8GtHVYXkaww==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YmUrM2hwdEdvQXNQRERk
            ZXpPaWs0anNVazB4Vlc2T0tteUp4MVlydWo0CkFFQnhuUTg1TzM3M2RrNUYyNmlv
            cGFTU0NMZXpoTXp2MkRaUmdJVVFJQUkKLS0tIGJFR1cvUFJnTWk4bjNIWlZUakNC
            UUxpK2x1T3h2dmxHa3RhTW1EUFp4Q28KS65tFDt8LRCm4ZiZNXBWOIzrAC56Cb4+
            s1/hUupYKPRAkVu48XDNTPpn2PFcXc8t8lg2+I3NdrgUjN4BNf37Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T06:44:37Z"
    mac: ENC[AES256_GCM,data:wV0krGHj4hdezbSW8Nds+qMoNQp8Xc2FQusHuCg5vZWFxm/EUI93hjPxBt/biTD8ehgLy0BR+4I1QxI0pXnLfKJJx+YmE/arl2xv0C5k3iMjQlX1E8sApxcg3F1Z/V4BioS563mMAoOlb7a+WJqp61Mv6FjDAJ7Y9BLuL+m+cYs=,iv:SUHEFVbuhuX653+b+AxjPzRd20oJd8ZfNKO5RejlN5I=,tag:oQ6YSErtlaRbcBZvmA7j1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
