prometheus-snmp-exporter:
    snmp:
        community: ENC[AES256_GCM,data:0ONPaawhOw==,iv:gZN+NjK0zX6BbVRzdi8Ob2HzB4QzUWhnZkqDU0maIyc=,tag:U2UsABZrdIFJnxj3OBsh9A==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YmUrM2hwdEdvQXNQRERk
            ZXpPaWs0anNVazB4Vlc2T0tteUp4MVlydWo0CkFFQnhuUTg1TzM3M2RrNUYyNmlv
            cGFTU0NMZXpoTXp2MkRaUmdJVVFJQUkKLS0tIGJFR1cvUFJnTWk4bjNIWlZUakNC
            UUxpK2x1T3h2dmxHa3RhTW1EUFp4Q28KS65tFDt8LRCm4ZiZNXBWOIzrAC56Cb4+
            s1/hUupYKPRAkVu48XDNTPpn2PFcXc8t8lg2+I3NdrgUjN4BNf37Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T20:55:46Z"
    mac: ENC[AES256_GCM,data:keIZM0hi7hGFR5OO3rlDy6ldIIEVtk4WBPHoci6j+hevTvM2FQoeWyRHikJ0Von8BE8cmfbeG2BHEOgZqQQoLrLgTI6BTJHtefx9YnKe+UsACjiy+NPs87zwiM+w+4eV3YVzv6/kze/KwmiAcf17i8rWbhyufofF+00Gc/rBm7c=,iv:SjZq0LZFwrhCBWOGFjsWEjUtRB8gTET5N+Bocf0YDl0=,tag:fpARKsyXqUUJIAY8SZ1eLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
