apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-config
  namespace: {{ .Release.Namespace }}
data:
  HOSTNAME: {{ .Values.hostname | quote }}
  DYNAMIC_CONFIG: {{ .Values.dynamicConfig | toString | quote }}
