apiVersion: v1
kind: Service
metadata:
  name: meshcentral
  namespace: {{ .Release.Namespace }}
  labels:
    app: meshcentral
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }}
spec:
  type: LoadBalancer
  selector:
    app: meshcentral
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
