apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/takanao14/homelab.git
    targetRevision: HEAD
    path: k8s/gateway
    helm:
      releaseName: gateway
      values: |
        domain: sandbox.butaco.net
        gatewayClasses:
          - name: envoy-gateway
            controllerName: gateway.envoyproxy.io/gatewayclass-controller
            enabled: true
        envoyProxies:
          - name: shared-gateway-envoy
            namespace: gateway-system
            enabled: true
            spec:
              provider:
                type: Kubernetes
                kubernetes:
                  envoyService:
                    externalTrafficPolicy: Cluster
        gateways:
          - name: shared-gateway-envoy
            namespace: gateway-system
            gatewayClassName: envoy-gateway
            enabled: true
            infrastructure:
              parametersRef:
                group: gateway.envoyproxy.io
                kind: EnvoyProxy
                name: shared-gateway-envoy
            listeners:
              http:
                enabled: true
              https:
                enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
