apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-bot-tokens
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: slack-bot-tokens
    creationPolicy: Owner
  data:
    - secretKey: bot-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.secret.key }}
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: {{ .Values.secret.botTokenProperty }}
    - secretKey: app-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.secret.key }}
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: {{ .Values.secret.appTokenProperty }}
