all:
  hosts:
    caddy01:
      ansible_host: 192.168.10.244
    ns1:
      ansible_host: 192.168.10.233
    ns2:
      ansible_host: 192.168.10.234
    dist1:
      ansible_host: 192.168.10.231
    dist2:
      ansible_host: 192.168.10.232
    syslog01:
      ansible_host: 192.168.10.243
    forgejo01:
      ansible_host: 192.168.10.245
    forgejo-runner01:
      ansible_host: 192.168.10.246
    netbox01:
      ansible_host: 192.168.10.247
    gpuvm01:
      ansible_host: 192.168.20.22
    pve:
      ansible_host: 192.168.10.10
    node1:
      ansible_host: 192.168.10.11
    node2:
      ansible_host: 192.168.10.12
    rpi3:
      ansible_host: 192.168.10.240
    rpi4:
      ansible_host: 192.168.10.241
    dev-cp1:
      ansible_host: 192.168.20.11
    dev-worker1:
      ansible_host: 192.168.20.12
    prd-cp1:
      ansible_host: 192.168.30.11
    prd-worker1:
      ansible_host: 192.168.30.12
    openbao1:
      ansible_host: 192.168.40.30
  children:
    dns:
      children:
        dns_auth:
          children:
            dns_primary:
              hosts:
                ns1: null
            dns_secondary:
              hosts:
                ns2: null
        dnsdist:
          hosts:
            dist1: null
            dist2: null

    openbao:
      hosts:
        openbao1: null

    syslog:
      hosts:
        syslog01: null

    forgejo:
      hosts:
        forgejo01: null

    forgejo_runner:
      hosts:
        forgejo-runner01: null

    netbox:
      hosts:
        netbox01: null

    gpuvm:
      hosts:
        gpuvm01: null

    caddy:
      hosts:
        caddy01: null

    dhcp:
      hosts:
        rpi4: null

    lxc:
      hosts:
        caddy01: null
        syslog01: null
        forgejo01: null
        netbox01: null
        ns1: null
        ns2: null
        dist1: null
        dist2: null

    proxmox:
      hosts:
        pve: null
        node1: null
        node2: null

    node_exporter:
      children:
        node_exporter_rpi:
          hosts:
            rpi3: null
            rpi4: null
      hosts:
        pve: null
        node1: null
        node2: null

    blackbox_exporter:
      hosts:
        rpi4: null
