modules:
  ix2106_ip_diagnostics:
    walk:
      - IP-MIB::ipInDiscards
      - IP-MIB::ipOutDiscards
      - IP-MIB::ipOutNoRoutes
      - IP-MIB::ipReasmFails
      - IP-MIB::ipFragFails
      - IP-MIB::ipFragCreates
      - IP-MIB::icmpOutDestUnreachs
      - UDP-MIB::udpNoPorts
      - UDP-MIB::udpInErrors
