image:
  repository: dxflrs/garage
  tag: v2.3.0

storage:
  data:
    size: 100Gi
    storageClassName: openebs-hostpath
  meta:
    size: 1Gi
    storageClassName: openebs-hostpath

s3Region: us-east-1

hostname: ""
webLoadBalancerIP: ""
publicBuckets: []

webui:
  enabled: false
  image:
    repository: khairul169/garage-webui
    tag: "1.1.0"
  hostname: ""
