apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: {{ .Release.Namespace }}
data:
  garage.toml: |
    metadata_dir = "/meta"
    data_dir = "/data"
    db_engine = "lmdb"
    replication_factor = 1
    consistency_mode = "consistent"
    rpc_bind_addr = "[::]:3901"

    [s3_api]
    s3_region = {{ .Values.s3Region | quote }}
    api_bind_addr = "[::]:3900"
    root_domain = ""

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ""
    index = "index.html"

    [admin]
    api_bind_addr = "[::]:3903"
    {{- if .Values.webui.enabled }}
    admin_token = "$GARAGE_ADMIN_TOKEN"
    {{- end }}
