apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: garage-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key
      remoteRef:
        key: k8s/garage/s3
        property: access-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: secret-key
      remoteRef:
        key: k8s/garage/s3
        property: secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: rpc-secret
      remoteRef:
        key: k8s/garage/s3
        property: rpc-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
