apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  serviceName: garage
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
        - name: garage
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3900
              name: s3
            - containerPort: 3901
              name: rpc
            - containerPort: 3902
              name: web
            - containerPort: 3903
              name: admin
          env:
            - name: GARAGE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage-secret
                  key: rpc-secret
            - name: GARAGE_DEFAULT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-secret
                  key: access-key
            - name: GARAGE_DEFAULT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-secret
                  key: secret-key
            {{- if .Values.webui.enabled }}
            - name: GARAGE_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: garage-webui-secret
                  key: admin-token
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/garage.toml
              subPath: garage.toml
            - name: data
              mountPath: /data
            - name: meta
              mountPath: /meta
      volumes:
        - name: config
          configMap:
            name: garage-config
            defaultMode: 0600
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: {{ .Values.storage.data.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.storage.data.size }}
    - metadata:
        name: meta
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: {{ .Values.storage.meta.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.storage.meta.size }}
