{{- if .Values.webui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-webui
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garage-webui
  template:
    metadata:
      labels:
        app: garage-webui
    spec:
      containers:
        - name: garage-webui
          image: {{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}
          ports:
            - containerPort: 3909
              name: http
          env:
            - name: API_BASE_URL
              value: "http://garage:3903"
            - name: API_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-webui-secret
                  key: admin-token
            - name: S3_ENDPOINT_URL
              value: "http://garage:3900"
            - name: S3_REGION
              value: {{ .Values.s3Region | quote }}
{{- end }}
