apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: {{ .Values.openbao.server | quote }}
      path: {{ .Values.openbao.path | quote }}
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.openbao.role | quote }}
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
