creation_rules:
  - path_regex: .*\.enc\.env$
    age: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
  - path_regex: .*\.enc\.yaml$
    age: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
  - path_regex: .*hosts\.enc\.yml$
    age: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
    encrypted_regex: ansible_user
  - path_regex: .*\.enc$
    age: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
  - path_regex: .*\.sops\.yaml$
    age: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
