creation_rules:
  # DHCP MAC addresses (hw_address only)
  - path_regex: ansible/inventories/homelab/group_vars/dhcp\.sops\.yaml$
    encrypted_regex: "^hw_address$"
    age: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v

  # Ansible group_vars secrets
  - path_regex: .*\.sops\.yaml$
    age: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
