apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amd-gpu-external
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/takanao14/homelab.git
    targetRevision: HEAD
    path: k8s/monitoring/charts/amd-gpu-external
    plugin:
      name: helm-secrets
      env:
        - name: HELM_VALUES
          value: "../../values/amd-gpu-external.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
