apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: dns-external
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
spec:
  metricsPath: /probe
  params:
    module: [dns_external]
  staticConfigs:
    {{- range .Values.dnsExternal.targets }}
    - targets: [{{ .ip | quote }}]
      labels:
        name: {{ .name | quote }}
    {{- end }}
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [name]
      targetLabel: instance
    - targetLabel: __address__
      replacement: {{ .Values.blackboxExporterURL | quote }}
  scrapeInterval: {{ .Values.scrapeInterval }}
