apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: icmp-network-devices
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
spec:
  metricsPath: /probe
  params:
    module: [icmp]
  staticConfigs:
    {{- range .Values.icmp.targets }}
    - targets: [{{ .ip | quote }}]
      labels:
        name: {{ .name | quote }}
    {{- end }}
  relabelings:
    # Set target IP as __param_target
    - sourceLabels: [__address__]
      targetLabel: __param_target
    # Set instance label to hostname
    - sourceLabels: [name]
      targetLabel: instance
    # Point scrape target to blackbox_exporter on rpi4
    - targetLabel: __address__
      replacement: {{ .Values.blackboxExporterURL | quote }}
  scrapeInterval: {{ .Values.scrapeInterval }}
