apiVersion: v1
kind: Service
metadata:
  name: lemonade-server-rocm
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: lemonade-server-rocm
  ports:
    - port: 13305
      targetPort: 13305
