---
- name: Deploy IX2106 DHCP lease observer
  hosts: dhcp_lease_observer
  serial: 1
  any_errors_fatal: true
  roles:
    - role: timezone
      tags: timezone
    - role: dhcp_lease_observer
      tags: dhcp_lease_observer
    - role: vector
      tags: vector
