prometheus-blackbox-exporter:
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
      icmp:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: "ip4"
      dns_external:
        prober: dns
        timeout: 5s
        dns:
          query_name: "google.com"
          query_type: "A"
          valid_rcodes:
            - NOERROR
      dns_internal:
        prober: dns
        timeout: 5s
        dns:
          query_name: "ns1.home.butaco.net"
          query_type: "A"
          valid_rcodes:
            - NOERROR

  extraManifests:
    - apiVersion: monitoring.coreos.com/v1
      kind: Probe
      metadata:
        name: icmp-network-devices
        namespace: monitoring
        labels:
          release: prometheus
      spec:
        interval: 60s
        module: icmp
        prober:
          url: blackbox-exporter-prometheus-blackbox-exporter:9115
        targets:
          staticConfig:
            static:
              - "192.168.10.1"
              - "192.168.10.2"
              - "192.168.10.10"
              - "192.168.10.11"
              - "192.168.10.12"
              - "192.168.10.240"
              - "192.168.10.241"
              - "192.168.10.242"
              - "192.168.10.253"
              - "192.168.10.254"
              - "192.168.110.11"
              - "192.168.110.12"
              - "192.168.20.22"
    - apiVersion: monitoring.coreos.com/v1
      kind: Probe
      metadata:
        name: dns-external
        namespace: monitoring
        labels:
          release: prometheus
      spec:
        interval: 60s
        module: dns_external
        prober:
          url: blackbox-exporter-prometheus-blackbox-exporter:9115
        targets:
          staticConfig:
            static:
              - "192.168.10.241"
              - "192.168.10.242"
    - apiVersion: monitoring.coreos.com/v1
      kind: Probe
      metadata:
        name: dns-internal
        namespace: monitoring
        labels:
          release: prometheus
      spec:
        interval: 60s
        module: dns_internal
        prober:
          url: blackbox-exporter-prometheus-blackbox-exporter:9115
        targets:
          staticConfig:
            static:
              - "192.168.10.241"
              - "192.168.10.242"
