kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      retention: 30d
      resourceSpec:
        requests:
          memory: 512Mi
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: prometheus.prd.butaco.net

  grafana:
    defaultDashboardsTimezone: jst
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
    persistence:
      enabled: true
      type: pvc
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    initChownData:
      enabled: false
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: grafana.prd.butaco.net
      externalTrafficPolicy: Local

  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
