prometheus-snmp-exporter:
  podAnnotations:
    reloader.stakater.com/auto: "true"
  extraArgs:
    - --config.file=/etc/snmp_exporter/snmp.yml
    - --config.file=/etc/snmp-exporter-auth/snmp-auth.yaml

  extraSecretMounts:
    - name: snmp-exporter-auth
      mountPath: /etc/snmp-exporter-auth
      secretName: snmp-exporter-auth
      readOnly: true

  extraManifests:
    - |
      apiVersion: monitoring.coreos.com/v1
      kind: Probe
      metadata:
        name: snmp-network-devices
        namespace: monitoring
        labels:
          release: prometheus
      spec:
        interval: 60s
        module: if_mib
        prober:
          url: snmp-exporter-prometheus-snmp-exporter:9116
          path: /snmp
        targets:
          staticConfig:
            relabelingConfigs:
              - action: replace
                targetLabel: __param_auth
                replacement: homelab_v2
            static:
              - "192.168.10.1"
              - "192.168.10.2"
