ansible_user: ENC[AES256_GCM,data:tVWOiw==,iv:36NvkBvc91J2zU63iw/JUEe7AoIIWYu/gfvjTmi0tRg=,tag:12z3S1F1Mo5m84Js8zlGWg==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdHJVdEYxU3RRN2N3c2ls
            QjJqYWh0YWdqcTJiaGZGcS8zdWVEQlRKK3hnCkdScGpRUWZGM3hxS3JWeUNyeWNp
            ZUdJTFk3NFRmaHRWUVAwRjA3WUZVcGsKLS0tIDNsQmd1UjVpcERyS3NmQVFXcW1Q
            dWR5ekE5MENHY2tZaGRMVHEyU2w5dTQKmAsPlwoW4uaAhlmUf3YyCCXB/woqlBYf
            aIiMKjazyhKmAZZ9Y0r2gSWpUKKQrZJzlyIZDCih2pXinJUxNlAFIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T16:06:56Z"
    mac: ENC[AES256_GCM,data:qrD5sK+0DsEGTVsITNJkBtYyaRf6JXjC+eVoqxZ+hujYIWwJeaZg9dmhD8Wh/0Hoy/Ds425aERSQ1oHgmJMs9yKsBBNyO5WFG8MxEa8gnDjPY6/sur3XOQZm4yZfH0l4i2r5vwNf1TwuXSzxqkROrYQMsJ9MkeCxhSKR5dfhui0=,iv:cdZGVWaC6ydU21vULl49rbnkzNdmfPL6dBgYuYxCKaI=,tag:LA830eaOtl2GGI+XhJQjzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
