ansible_user: ENC[AES256_GCM,data:27tnUw==,iv:BBuMXbyY02eV/wTgTWx1dWlSNQDK+gjJcTMwMAJf/+k=,tag:l5HuZPAT3MtIXX8Y3/A1Tw==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dnBXMTIxMjNabkJ0bG1r
            MytqNXdUVzdZS3R4RkVtTy81a0t0MkcxUlFzCklFUUlBcUhaTDc4bUZUd0YwSnF3
            NFVWZlZ3N0gvV3k2cnVxVXlZWlVUZWcKLS0tIHNEUVZQbTh6UERxQkE5Sy90aUxK
            bzVNeE9IMHhJcmRCSmtKclBNREgrUUkK/f+8Rtp/hMkKtV0CqOYvFZ3iSDeYRCuO
            iuNkrJkRSa3TCo3vSOZWXlBcGQdhsypKC56duG9L/BqsDs9AnPLorg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T07:54:13Z"
    mac: ENC[AES256_GCM,data:/lwfbZSHDsiATQ5jnBwBm4oH+6k6JO5si34OO0Vzjx344ndMRcZIciwjSUcmHv7Md6qEyyv3NFtIrXGIMFQxi2VQ1dzCVI11twx7ro1Ivy0vOT3QrMvGmFXo5KP+xU/8pQuGG/JaecEzyH47H2P8eD3bath5ya4ppaD7wjgY/9o=,iv:tbNNHUgo4sMy+6iRNnSCEasOiMcIV0bWaK8wnlQYHwI=,tag:lTd5KTXe3xwdxooLfqH2/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
