ansible_user: ENC[AES256_GCM,data:L3EeQw==,iv:BbyumY/LsOHPDUMJ/XHJoUxz1UpeL3DB5C4scmIfWfg=,tag:G0bnVxzuLVln3RJi8rd8dw==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOGEvR0I3TjlzaUN6cXNS
            K2oyMXdvOERNMUIrSVFrR1FMNWM3RVppL2dBCjVtbDU1Uzd0K3RhT2tsam5VVkVp
            Y0JCL09tWTFISkxzektUYW1GOVJjTWcKLS0tIHU4VnI3ZTc2N01sanNmdzFRWTEv
            TzlQMzNXZFRPQTJaWlJnQXR6NkF4NDAKr/VOZuyfdjiAUcaklBwfa35XLFhwAWjq
            8EcAR9x+euUIgwVT0uCd1jpLFqdhutOkox3UyPkqD7AhEHDbXD7DRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T07:53:53Z"
    mac: ENC[AES256_GCM,data:iUCk35gGWhOS0+XDAADQOddscadC9NqrKOY8Cgym5cGBsz9+KaJgbo98bJNA7dANMBRllQgoe7WGVrkCLWxW3Wz5HjnMqED2hi/Qv1fgkF3rRqpnAo6BIVLufnjaaOteb4mCdU9kAJdc/Mje1Ik1Uc8xw08368wn4EIWt81O+xE=,iv:J2KkPsDnXPYqaDvohZvVzoXHwnJotuLQitmt+DQdL5o=,tag:+I3jeXxUwdgp8tS4ZLC9dA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
