ansible_user: ENC[AES256_GCM,data:4g83ag==,iv:lWVEk3YssoNu2D5qTfFAxDGjvr8TF/n3COiV/D8xYqk=,tag:5jfXhQLXojOnG76KoSOxVQ==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNEpOTWJ2M0V0c0F5OUtp
            aWJmK2J3WVNadno3SVlxZnBPZ201MU00YlFvCm9xbU5IQXE2QmJhOHJHdXM1OXpN
            b3BUUnZINVdvcElSZU45c3Z6TFVibjQKLS0tIFlIVGJFZkt1a0xnc2ZLSUY3ZnpQ
            bkJlRmFqOTArNmFmWXJ4L29HM21NNjQKBD/grq92MOT6uQ8fS4t79gO7BCMHdmuB
            XKCMv+jama9OxO70VbohVrTF3OnQkfM03uolCRVFqWytTBbJw1wndQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T07:08:48Z"
    mac: ENC[AES256_GCM,data:FG98bsL4McaclOxMRJEoKT8VsNtuUMTfYj0YC/2LojkJn8WlkkXeiRj9ZdNTMSNJ0gs7xL5SqlElqylyPD3W125IndgUbc5um6HGyWP1r35Csiy/4Q2CWY930VAN0FV3pB/NuA2oHLcQJo67S9NJbbKOjFUcsS3B9q+IWahFot8=,iv:AnD7HgPu3FAVmtl6XpaomjqeXaL28jRoO98kCLdV6/I=,tag:8YIrabo+3nCB2CVuprr8fg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
