apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: snmp-exporter-auth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: snmp-exporter-auth
    creationPolicy: Owner
    template:
      data:
        snmp-auth.yaml: |
          auths:
            homelab_v2:
              community: {{ "{{ .community }}" | quote }}
              version: 2
  data:
    - secretKey: community
      remoteRef:
        key: k8s/monitoring/snmp-exporter
        property: community
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
