---
- name: Upgrade all packages to the latest version on Debian Series
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Upgrade all packages to the latest version on Red Hat Series
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true
  become: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"
