apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pve-exporter-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: pve-exporter-config
    creationPolicy: Owner
    template:
      data:
        pve.yml: |
          cluster_dev:
            user: {{ "{{ .clusterDevUser }}" | quote }}
            token_name: {{ "{{ .clusterDevTokenName }}" | quote }}
            token_value: {{ "{{ .clusterDevTokenValue }}" | quote }}
            verify_ssl: false
          cluster_prd:
            user: {{ "{{ .clusterPrdUser }}" | quote }}
            token_name: {{ "{{ .clusterPrdTokenName }}" | quote }}
            token_value: {{ "{{ .clusterPrdTokenValue }}" | quote }}
            verify_ssl: false
          cluster_prd2:
            user: {{ "{{ .clusterPrd2User }}" | quote }}
            token_name: {{ "{{ .clusterPrd2TokenName }}" | quote }}
            token_value: {{ "{{ .clusterPrd2TokenValue }}" | quote }}
            verify_ssl: false
  data:
    - secretKey: clusterDevUser
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-dev-user
    - secretKey: clusterDevTokenName
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-dev-token-name
    - secretKey: clusterDevTokenValue
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-dev-token-value
    - secretKey: clusterPrdUser
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-prd-user
    - secretKey: clusterPrdTokenName
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-prd-token-name
    - secretKey: clusterPrdTokenValue
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-prd-token-value
    - secretKey: clusterPrd2User
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-prd2-user
    - secretKey: clusterPrd2TokenName
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-prd2-token-name
    - secretKey: clusterPrd2TokenValue
      remoteRef:
        key: k8s/monitoring/pve-exporter
        property: cluster-prd2-token-value
