apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter-config
  namespace: {{ .Release.Namespace }}
stringData:
  pve.yml: |
    {{- range $name, $creds := (index .Values "prometheus-pve-exporter").pveConfig }}
    {{ $name }}:
      user: {{ $creds.user | quote }}
      token_name: {{ $creds.token_name | quote }}
      token_value: {{ $creds.token_value | quote }}
      verify_ssl: false
    {{- end }}
