apiVersion: v1
kind: Service
metadata:
  name: prometheus-pve-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus-pve-exporter
spec:
  selector:
    app: prometheus-pve-exporter
  ports:
    - name: metrics
      port: {{ .Values.port }}
      targetPort: metrics
