apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-ui-basic-auth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.openbao.secretStore.name }}
    kind: {{ .Values.openbao.secretStore.kind }}
  target:
    name: longhorn-ui-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: .htpasswd
      remoteRef:
        key: {{ .Values.openbao.basicAuth.key }}
        property: {{ .Values.openbao.basicAuth.property }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
