headlamp:
  config:
    extraArgs:
      - "-kubeconfig=/headlamp/dev-kubeconfig:/headlamp/prd-kubeconfig"
      - "-in-cluster=false"
  volumeMounts:
    - name: dev-kubeconfig
      mountPath: /headlamp/dev-kubeconfig
      subPath: kubeconfig
      readOnly: true
    - name: prd-kubeconfig
      mountPath: /headlamp/prd-kubeconfig
      subPath: kubeconfig
      readOnly: true
  volumes:
    - name: dev-kubeconfig
      secret:
        secretName: headlamp-dev-kubeconfig
    - name: prd-kubeconfig
      secret:
        secretName: headlamp-prd-kubeconfig
  httpRoute:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: shared-gateway-envoy
        namespace: gateway-system
        sectionName: https
