{{- if .Values.externalSecretAlertmanager.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: alertmanager-discord
    creationPolicy: Owner
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        key: k8s/monitoring/alertmanager
        property: discord-webhook-url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
{{- end }}
