apiVersion: v1
kind: Endpoints
metadata:
  name: pdns-auth-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: pdns-auth
    release: prometheus
subsets:
  - addresses:
      {{- range .Values.targetIPs }}
      - ip: {{ . | quote }}
      {{- end }}
    ports:
      - name: metrics
        port: {{ .Values.port }}
        protocol: TCP
