---
- name: reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart netbox
  become: true
  ansible.builtin.service:
    name: netbox
    state: restarted

- name: restart netbox-rq
  become: true
  ansible.builtin.service:
    name: netbox-rq
    state: restarted

- name: restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
