apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-node-exporter-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: external-node-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: {{ .Values.metricsPath }}
