k8sServiceHost: "192.168.100.10"
k8sServicePort: "6443"
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]
prometheus:
  enabled: true
