repositories:
- name: cilium
  url: https://helm.cilium.io

releases:
- name: cilium
  namespace: kube-system
  chart: cilium/cilium
  version: 1.17.4
  # 以下は必須ではない
  values:
  - k8sServiceHost: "192.168.20.21" # Control Planeのホスト名またはIPアドレス
  - k8sServicePort: "6443"
  - kubeProxyReplacement: true
  - hubble:
      relay:
        enabled: true
      ui:
        enabled: true
  - ipam:
      operator:
        clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"] # CIRDはあくまで一例
