apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: code.forgejo.org
      chart: forgejo-helm/forgejo
      targetRevision: 10.0.0
      plugin:
        name: helm-secrets
        env:
          - name: HELM_VALUES
            value: "$ARGOCD_APP_SOURCE_values/k8s/forgejo/values.yaml,secrets://$ARGOCD_APP_SOURCE_values/k8s/forgejo/secrets.enc.yaml"
    - repoURL: https://github.com/takanao14/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
