apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/takanao14/homelab.git
    targetRevision: HEAD
    path: k8s/gateway
    helm:
      releaseName: gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
