apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/takanao14/homelab.git
      targetRevision: HEAD
      path: k8s/headlamp/chart
      helm:
        releaseName: headlamp
        valueFiles:
          - $values/k8s/headlamp/values.yaml
    - repoURL: https://github.com/takanao14/homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
