gitea:
    admin:
        username: ENC[AES256_GCM,data:KT8CHUyrqY4=,iv:reBOE4WfL60SUQij1+c6Zrj+XMxDitDXmESrPluKgAM=,tag:Qh/Gs9rbhRFkVz7mJcHPtA==,type:str]
        password: ENC[AES256_GCM,data:X+4eI4RBqUNCnUE=,iv:2kJRAOZZhlCHPJv02KLcr6TBz6SWc9pTD06tGeBVFB0=,tag:3KI5aZciU1lIaj4Im/2EVg==,type:str]
        email: ENC[AES256_GCM,data:6j1rH3sgj2dE0C2MJUB5Zw==,iv:Y/xElTh1dj/1iOuVPwjw8UrIvz20HSOzwjE7OAa4iac=,tag:2bVfTKoMrfWGLhQulrbeYA==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUDhPR2dJTk92aUdZcG4v
            RUFVTFR2bmRZVkEwaVlFZ2UyMjJCUnBGNVVNCmMzSEVKY1FFUDZaa3hhb0pLWVZv
            S0VFNmpHWEQ0M2x6Y1JHOU95YjFGdDAKLS0tIGJLN283bEdWRnNuZEJZVDdDeWNy
            ZHorWVdvRlZLQUk2TUd3eW8vekRuWHcKs0XjqoQheXIrNkYgEh+1I12SGtM0WAe6
            hfzhQNJBwYjtfQ6SNk7fufAevGlvgEnSzzrYyXSbzohcjSy9jWAaMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T08:45:44Z"
    mac: ENC[AES256_GCM,data:XeR8T11U4aAVyAgtH2OelQmFxu9ZKr4Hxwz/H1AFybpT+cGSkIzeKSn9/1bNng8TCZOdiEdLQRicaFpqAcfKL45vuYoUfxdctR8IIpQyptBrpYUFT25GeHXljqiM5pBkwOZfwUR+X0/N+zyGj7dOEDrZ7l5bTjLB8BoyJSZMjjY=,iv:gXG4uBt/BJl2i2CslGPLkas+dwFDsmhUodVbsYPz6Yo=,tag:L85cLggiIFP0/C14eZiQCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
