gitea:
    admin:
        username: ENC[AES256_GCM,data:2mhqM8LvwBs=,iv:gF7q4LRYK+96j9dSKrdAsF5Pei2QXKQ9QZk8R7T3Uik=,tag:fh/tkzKkQeAPFM2j6fx3SQ==,type:str]
        password: ENC[AES256_GCM,data:F8f06xo8Xe/QCBg=,iv:HrMo5AT9BYz9hkGAzb6fn2aWFoCmQN/AhNL/F/2sLZE=,tag:xWR6CSO6iBsoG1PqG+q/Dw==,type:str]
        email: ENC[AES256_GCM,data:47usx57WXAIrP7pc1geeXg==,iv:Uz1ghBmkUeoWFZOBTwABgrmQKyKmKLg8KPs4Lz/a5X8=,tag:NsXiqrSoenKaozOfmG/pLA==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV1NJNFUxREhSdzJmM1ho
            ejVOWXEwdHNiTVN4M2UwM3RycFR0R1B1RlJFCjN2dXpaYnlLUWlGaGhsTU11MFdD
            OHhVMHcwdUxFNUQ4THRPVytVUVNOODgKLS0tIEcrd0VaenNPcnhrZUtEeGdoRmhW
            WTdkb1hoQnp6dTFvVGRXK2pDREhhbmMKYej98GavsAgqfVZ/P7gW6ueSM8d7CQA6
            5uAcJbFbkHjjV2soHLUvM7QZ7SdGf0jfjkTI1GUqpMb7dRb3db97mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T08:56:40Z"
    mac: ENC[AES256_GCM,data:kbd79GtR9625stgN1ZwiKUIoKBvWLAHbdZCz6fuQMJi7Rhf8Lc81K59exM1kbpo2vaAUNh+ZSQHDZ6TpmJFp+QCXfp24d/BM1aiZ+mt7qgocmb7+EqCFfVHumICAaEPU+hrN1FvJBEmWI6pHEE6oqZRuysqwXDPOSHbIyJfF+MM=,iv:spNrzBgt7f9jT7Uq9u5+drSrs4bjA8lVo73wetDeCgk=,tag:83EKfx9nJyBTji3SzfsP4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
