hostname: www.prd.butaco.net
namespace: homepage

image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.12.3

proxmox:
  prd:
    url: https://node1.home.butaco.net:8006
    node: node1
  dev:
    url: https://pve.home.butaco.net:8006
    node: pve
  prd2:
    url: https://node2.home.butaco.net:8006
    node: node2

pdns:
  primary:
    addr: pdns1.home.butaco.net
    pveNode: node1
    pveVmid: "103"
    pveType: lxc
  secondary:
    addr: pdns2.home.butaco.net

dnsdist:
  dnsdist1:
    addr: dnsdist1.home.butaco.net
    pveNode: node1
    pveVmid: "103"
    pveType: lxc
  dnsdist2:
    addr: dnsdist2.home.butaco.net

truenas:
  url: http://truenas.home.butaco.net
  node: node1
  vmid: "100"
  key: ""

grafana:
  url: https://grafana.prd.butaco.net
  username: admin
  password: ""

prometheus:
  url: https://prometheus.prd.butaco.net

prdArgo:
  url: https://argocd.prd.butaco.net

devArgo:
  url: https://argocd.dev.butaco.net

forgejo:
  url: http://forgejo.home.butaco.net/

meshcentral:
  url: https://meshcentral.dev.butaco.net

network:
  bgw1: bgw1.home.butaco.net
  c1200: c1200.home.butaco.net
  wifiAp1: wifiap1.home.butaco.net
  wifiAp2: wifiap2.home.butaco.net
