---
# renovate: datasource=gitea-releases depName=forgejo/runner registryUrl=https://code.forgejo.org
forgejo_runner_version: "12.9.0"
# renovate: datasource=github-releases depName=StackExchange/dnscontrol
dnscontrol_version: "4.36.1"
forgejo_runner_user: runner
forgejo_runner_group: runner
forgejo_runner_home: /var/lib/forgejo-runner
forgejo_runner_binary: /usr/local/bin/forgejo-runner
forgejo_runner_config: /etc/forgejo-runner/config.yml

forgejo_runner_url: "http://forgejo.home.butaco.net"
forgejo_admin_token: ""
forgejo_runner_name: "{{ inventory_hostname }}"
forgejo_runner_labels:
  - "self-hosted:docker://catthehacker/ubuntu:act-24.04"
  - "ubuntu-24.04:docker://catthehacker/ubuntu:act-24.04"
