headlamp:
  namespaceOverride: headlamp
  httpRoute:
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: shared-gateway-envoy
        namespace: gateway-system
        sectionName: https
    hostnames:
      - headlamp.prd.butaco.net
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - group: ""
            kind: Service
            name: headlamp
            port: 80
            weight: 1
