apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: seaweedfs-s3-secret
    creationPolicy: Owner
    template:
      data:
        seaweedfs_s3_config: |
          {"identities":[{"name":"admin","credentials":[{"accessKey":"{{ `{{ .accessKey }}` }}","secretKey":"{{ `{{ .secretKey }}` }}"}],"actions":["Admin","Read","Write","List","Tagging"]}]}
  data:
    - secretKey: accessKey
      remoteRef:
        key: k8s/seaweedfs/s3
        property: access-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: secretKey
      remoteRef:
        key: k8s/seaweedfs/s3
        property: secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
