cloudflare:
    apiToken: ENC[AES256_GCM,data:Zc8LFfpxBvvhKG0JtOndL+LnDUAIFn0eImnJ1vQNrjLx/oyoGUrftN1lfYeaQ/PSZfaSscs=,iv:PawN0RTvqOQ2y9f470YG5B0/B2imN4m28uAqO/U5Fzw=,tag:hIxX9EVjz6lrqhyJ/ssG0w==,type:str]
    email: ENC[AES256_GCM,data:P6vhSYZDDibYHSDlek0bUmp+7A==,iv:7s/gfAbufSqIciGcM7VFuOQ/T1CN+Zpcj1PCC4a9kU0=,tag:NVAdC3MnonYqv82hemacTw==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWGxRdi91VXhrUXEzK3p2
            cVNhTkJKbHhJVTJMaDhhWGZGaFN5OWFVRFhrCktjTmZEd1R6ZmY4SFlmaHJCbmZY
            cHp2MkI2eTNwYjdtRzgzeWtjVlZNVEUKLS0tIGtXcjZVaGFrb05aazhIMVBqWWkr
            MmU2cWRoanpCRUtLWmNUV3FWSG1IYkUKIQQK2bf1BY1ghhjpM4Ts+inpsp5a0pgQ
            ZTy00Wc09nE1wiGThSQuabFj/9tMD7isG+5pN/tuaIFo+XnYRrzjVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T03:28:42Z"
    mac: ENC[AES256_GCM,data:z2bctwEUpcuTIBgvcSwPjV6jPztfWtSXETm+8L4fyhfwbc4hNaV3sSj99a9Bw2oVab3spdyUKvKTiN4W2vz3Bs3MXJs7EbmEHWwni9y+BXPIhJnYoCa/OdpIuKSwaYz8F65mlQmzHWDUo3rtOnj4jcna5G/pHppqVyjLR4bOnAg=,iv:S/QMlPX+MySpm5cSQciekM+/cvk2DzHZLB7lZB4Ys/A=,tag:sQpba/Z12+5gz70laIi8zA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
