{{- $app := index .Values.apps "ollama" }}
{{- if $app.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ $app.wave | quote }}
spec:
  project: default
  sources:
    - repoURL: {{ .Values.repo.url }}
      targetRevision: {{ .Values.repo.targetRevision }}
      path: k8s/ollama/chart
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $values/k8s/ollama/values.yaml
          - $values/k8s/ollama/{{ include "argocd-apps.env" . }}/values.yaml
    - repoURL: {{ .Values.repo.url }}
      targetRevision: {{ .Values.repo.targetRevision }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
