{{- $app := index .Values.apps "reloader" }}
{{- if $app.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: {{ $app.wave | quote }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.targetRevision }}
    path: k8s/reloader
    helm:
      releaseName: reloader
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
