apiVersion: v2
name: envoy-gateway-crds
description: Envoy Gateway CRDs wrapper
type: application
version: 0.1.0
dependencies:
  - name: gateway-crds-helm
    version: 1.8.3
    repository: oci://docker.io/envoyproxy
