domain: ""

gatewayClasses: []

envoyProxies: []

gateways:
  - name: shared-gateway
    namespace: gateway-system
    gatewayClassName: cilium
    enabled: true
    listeners:
      http:
        enabled: true
      https:
        enabled: true
