apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  namespace: vault
spec:
  size: 1
  image: hashicorp/vault:1.18.4
  bankVaultsImage: ghcr.io/bank-vaults/bank-vaults:v1.31.1

  unsealConfig:
    kubernetes:
      secretNamespace: vault

  config:
    storage:
      raft:
        path: /vault/file
        # 最初のノードが自分自身をサービス経由で探さないように、明示的に指定
        retry_join:
          - leader_api_addr: "http://127.0.0.1:8200"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        cluster_address: "0.0.0.0:8201"
        tls_disable: true
    api_addr: "http://127.0.0.1:8200"
    cluster_addr: "http://127.0.0.1:8201"
    ui: true

  externalConfig:
    auth:
      - type: kubernetes
        path: kubernetes
        roles:
          - name: eso-prd
            bound_service_account_names: ["external-secrets"]
            bound_service_account_namespaces: ["external-secrets"]
            policies: ["eso-readonly"]
            ttl: 24h
          - name: eso-dev
            bound_service_account_names: ["external-secrets"]
            bound_service_account_namespaces: ["external-secrets"]
            policies: ["eso-readonly"]
            ttl: 24h

    secretEngines:
      - path: secret
        type: kv
        options:
          version: "2"

    policies:
      - name: eso-readonly
        rules: |
          path "secret/data/*" {
            capabilities = ["read"]
          }
          path "secret/metadata/*" {
            capabilities = ["list"]
          }

  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
