---
- name: Reboot if needed
  ansible.builtin.stat:
    path: /run/reboot-required
  register: reboot_required

- name: Reboot if needed
  ansible.builtin.reboot:
    msg: "Rebooting because /run/reboot-required exists"
  when: reboot_required.stat.exists
  become: true
