---
- name: Create Proxmox maintenance user
  hosts: proxmox
  any_errors_fatal: true

  roles:
    - role: maintenance_user
      maintenance_user_force: true
      tags: maintenance_user

  tasks:
    # Set access permissions for Proxmox GUI (Web UI)
    - name: Check if user exists in Proxmox
      become: true
      ansible.builtin.shell: "pveum user list | grep -q '{{ maintenance_user }}@pam'"
      register: pve_user_exists
      check_mode: false
      changed_when: false
      failed_when: false

    - name: Add user to Proxmox VE
      become: true
      ansible.builtin.command: "pveum user add '{{ maintenance_user }}@pam' --comment 'Managed by Ansible'"
      when: pve_user_exists.rc != 0

    - name: Check Administrator role
      become: true
      ansible.builtin.shell: "pveum user permissions '{{ maintenance_user }}@pam' | grep -q 'Administrator'"
      register: pve_user_perm
      check_mode: false
      changed_when: false
      failed_when: false

    - name: Grant Administrator role to user
      become: true
      ansible.builtin.command: "pveum acl modify / -user '{{ maintenance_user }}@pam' -role Administrator"
      when: pve_user_perm.rc != 0
