---
- name: Setup SeaweedFS
  hosts: seaweedfs
  roles:
    - role: timezone
      tags: timezone
    - role: seaweedfs
      tags: seaweedfs
    - role: vector
      tags: vector
    - role: journald
      tags: journald
