---
- name: Determine if maintenance user should be created
  ansible.builtin.set_fact:
    _maintenance_user_should_run: "{{ ansible_facts['virtualization_type'] == 'lxc' or maintenance_user_force | bool }}"

- name: Setup maintenance user
  block:
    - name: Validate required environment variables
      ansible.builtin.assert:
        that:
          - maintenance_user | length > 0
          - (maintenance_ssh_key | length > 0) or (maintenance_ssh_key_path | length > 0)
        fail_msg: "Required variables (maintenance_user, etc.) are missing. Check your group_vars or environment."

    - name: Ensure sudo is installed
      become: true
      ansible.builtin.apt:
        name: sudo
        state: present
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"

    - name: Create the maintenance user
      become: true
      ansible.builtin.user:
        name: "{{ maintenance_user }}"
        password: "{{ maintenance_password_hash | default(omit) }}"
        shell: /bin/bash
        groups: sudo
        append: true
        create_home: true
        state: present

    - name: Configure passwordless sudo for the user
      become: true
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ maintenance_user }}"
        content: "{{ maintenance_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
        validate: /usr/sbin/visudo -cf %s

    - name: Add maintenance SSH authorized key
      become: true
      ansible.builtin.authorized_key:
        user: "{{ maintenance_user }}"
        state: present
        key: "{{ maintenance_ssh_key | default(lookup('file', maintenance_ssh_key_path | expanduser)) }}"
      when: (maintenance_ssh_key | length > 0) or (maintenance_ssh_key_path | length > 0)
  when: _maintenance_user_should_run
