authentik_bootstrap_email: ENC[AES256_GCM,data:cceKsX86/AB0ozZ6OmmGsUHucw==,iv:W1nL/+h3UJcH9OufDTo4Bb0cuZg7qJ8+x/WjV9JUl/g=,tag:LgTm5gAtMNMOu2qHDhbwlw==,type:str]
authentik_bootstrap_password: ENC[AES256_GCM,data:cbQ2KStc2bF5i0Q=,iv:ODgYHpB6bhCppsZEnzrCQxDjcGoWJRkKtyTElY9w0DA=,tag:7Wgup0OHkhNKyhIhPkUemg==,type:str]
authentik_bootstrap_token: ENC[AES256_GCM,data:j8bPyuZw1e9MSOUp27FoAXUmDy8U4NFssK9WsPddorvBaAlnGvGFSs6CzsGvmnyZOv+EHVy/0tSABp3b2Qv9Yw==,iv:asZUknchfPgEaV2sUHSUDtPw1MvFyyj30vmSAKb7HcE=,tag:vWl1KeO4Hg6ECjv1fo+WPw==,type:str]
authentik_ldap_bind_password: ENC[AES256_GCM,data:pxATPNvK3G9G1VOlldMVNRwwpyeY2EKAqw2vmrO1JA==,iv:EyzBynd3lAkyWKv3P6XyjQkqWnVxbl2mgCVb7vlVLr8=,tag:dw4z39K7BAuJUNHUfknTTg==,type:str]
authentik_pg_pass: ENC[AES256_GCM,data:ch1llFFPaeelra9etWceHl8ZoajrIyvYhsk57qgOpBuPw0Y86t83pazIV732W4Aj,iv:3SKUbxDFhYnAh7QsDV+yXyCCKhIuAC+CPa+lsroyVjs=,tag:R8xTEOUkyowirFnC+hUQCQ==,type:str]
authentik_secret_key: ENC[AES256_GCM,data:A28K2Mk2IDDR1JHjE2ObnF3tvdK+9MGmyZNKnLdM4o58jLPeqD5GiudhjUPjd8d7erZN07NimJj+LtlqgR4r/jt/oEEuCjmgdwEDpJ3HAvk=,iv:0Hg0w5r8NPLgAi6goWHaPPhT+UL0cpArfmLTL0e31mE=,tag:PTCkornqwxGSK01rehluhA==,type:str]
authentik_test_user_password: ENC[AES256_GCM,data:UY8iKjhYtUALF70H4QXRODcA14R3IJeSV2VCpNS+sQ==,iv:9jVaCdYouTJl6oKW1a8lFVitQvg4x0/SzI67hjYtRV8=,tag:xyHFTE+PO0tNInyv8zrQ1w==,type:str]
authentik_test_user_username: ENC[AES256_GCM,data:vk/s2tCW10A=,iv:TCVOdAj+yIt9c+RlUWpblctcHxgFQwyoP9UqvLUY89o=,tag:0SxD/oNMMzrUAqf6fCd/DQ==,type:str]
authentik_users:
    - username: ENC[AES256_GCM,data:aiQyzGoo5w==,iv:JKf/e/uU760pKnmIS1ZJKYsU++KTe/TN+v0mI76opmY=,tag:UVmRLmZlySGOmRY4UeBLaQ==,type:str]
      password: ENC[AES256_GCM,data:nuiY9rec9o+RZQ==,iv:qYWPw54QPacqnQTW2AVIaLvh/XbcBvx909XbsbXr6wo=,tag:yf+XUDR9FirW5BK80nTaxQ==,type:str]
      groups:
        - ENC[AES256_GCM,data:CyCx0d0mCHQPFS4SJ9itvg==,iv:s2RqM5P3oCbIaFlL8SybUmTVZWLWVTvmmsmOy1EDg1c=,tag:E8ZsjEZkD/18IC5jwkYYIA==,type:str]
        - ENC[AES256_GCM,data:WHUCv9nTs1Wx8wNLImXC4oaW3g==,iv:oWb+NQ5ivCrw97cLiZjdJa+U8/W87Rvlrku1uePbUY0=,tag:c6XShLGQzlsQLH8WJ+OOtw==,type:str]
        - ENC[AES256_GCM,data:rt8VvRAYezeFbRdb0g85,iv:ek7U++L4A6PGGuTPIvS1msPqlNSC/2S3KKdBT87yIBc=,tag:9CG8sbQKw46sLXJIzS3FcA==,type:str]
        - ENC[AES256_GCM,data:NZrqDKrnGc6ruw23Eurqkw==,iv:INVgaHs1Tp9fu3agbewEs4M2ZXw1PvKjHa5+qHVA74c=,tag:vxM9iIgsB+bxPM9zmMWnow==,type:str]
    - username: ENC[AES256_GCM,data:QQ5dUtnOJw==,iv:xJq0NNrvKmMkT6uyicd0xR3QJlmGbYznAF4j7xuHJ7Q=,tag:zs3CuWOq4rOO/rDK1HlODg==,type:str]
      password: ENC[AES256_GCM,data:qF+f5KHFErPU5w==,iv:m7z/tczbuBbiQxaHalAlhUor2GqMfbAK/ONsQ3HXJoI=,tag:bd6M4eUoJbVXlrvTuM8DSg==,type:str]
      groups:
        - ENC[AES256_GCM,data:WHUCv9nTs1Wx8wNLImXC4oaW3g==,iv:oWb+NQ5ivCrw97cLiZjdJa+U8/W87Rvlrku1uePbUY0=,tag:c6XShLGQzlsQLH8WJ+OOtw==,type:str]
        - ENC[AES256_GCM,data:rt8VvRAYezeFbRdb0g85,iv:ek7U++L4A6PGGuTPIvS1msPqlNSC/2S3KKdBT87yIBc=,tag:9CG8sbQKw46sLXJIzS3FcA==,type:str]
        - ENC[AES256_GCM,data:NZrqDKrnGc6ruw23Eurqkw==,iv:INVgaHs1Tp9fu3agbewEs4M2ZXw1PvKjHa5+qHVA74c=,tag:vxM9iIgsB+bxPM9zmMWnow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocUI2TWRmNEJtNHZjeHZa
            Z3pPZWUzRjJNYnJCcVllZ2tIeUNHeTJERWxrCmtCRXlaUzR6bEJqa0lEZ2pPYnJm
            aitDT2hpR1ltK1ZYdHlBdnVYa0d6QUUKLS0tIDVLNFkxZm5laUJrZFZmb2lEUm9O
            STB2M3AwM0hVTEVVWDZEeEZHUXlROVEK/z6yWPFTAG/z7HVAgOIUF7ariCUP+kui
            WLSt8AbZ5oUJtpSl0WBi+16d79EsrBvEdhaJcosXwmzwPfbowR48CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
    lastmodified: "2026-09-05T03:52:37Z"
    mac: ENC[AES256_GCM,data:IPDyuwAkwlP9oj2987WYnwU36ndCa8LX46qU7Dkz391bPTpaiy7s+pAltosP2v7HixmJ7yR0Z6K/X9wZ/qyf/Pjqt7a5c3VzlxjZD3Hiwdht+8P049D6MV5cwzErNieE1FRKcNyk7o/HHT39T63PWSLWI7rS7u+Q24iFJdgUCFg=,iv:mq/k8c9EwWq3kwpNrEX1Epeacn9xnaaBD34PISpxEIQ=,tag:IuQCVWW+NTbQfmxJ0wmMSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
