---
caddy_ip: "192.168.10.244"
caddy_upstreams:
  - hostname: pdns1.home.butaco.net
    backend: 192.168.10.242:8081
  - hostname: pdns2.home.butaco.net
    backend: 192.168.10.241:8081
  - hostname: dnsdist1.home.butaco.net
    backend: 192.168.10.242:8083
  - hostname: dnsdist2.home.butaco.net
    backend: 192.168.10.241:8083
  - hostname: forgejo.home.butaco.net
    backend: 192.168.10.245:3000
  - hostname: truenas-ui.home.butaco.net
    backend: 192.168.20.10:80
  - hostname: netbox-ui.home.butaco.net
    backend: 192.168.10.247:80
