---
comfyui_host: "0.0.0.0"
comfyui_port: 8188
comfyui_checkpoints:
  - filename: sd_xl_base_1.0.safetensors
    url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors
