kea_subnet4:
    - subnet: 192.168.110.0/24
      pool: 192.168.110.30 - 192.168.110.127
      routers: 192.168.110.1
      dns_servers: 192.168.10.242,192.168.10.241
      domain_name: home.butaco.net
      reservations:
        - hw_address: ENC[AES256_GCM,data:/KLeSqWr7/1t+CUyuw8ZjlU=,iv:1sl+AIsxvV1Blgqg8pAY8IazAL9Tiy3odvOi9ZOOmUM=,tag:57LdArDdgqkVmvTRU4DV7w==,type:str]
          ip_address: 192.168.110.11
        - hw_address: ENC[AES256_GCM,data:vYrdpuMpf8fnHCX0giv0964=,iv:RC5V/IOcrFW91CB87QsWdLTQKG6n3MeruPcrpR2aHTc=,tag:UHV1URl2ed+XFZIHrWu5uQ==,type:str]
          ip_address: 192.168.110.12
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV2pEaDdHMkZ6Y2pidnVo
            N3BtbVFxUXJLVzBXaytTY0VPTWlaSFo3a2hRCkxjOUw3b3lTaUJTRWxkRW9LSm9U
            TG5nc0VNVnVTUEVSazRzOHZpTlMzQ0kKLS0tIFlUSng3RlZ3QlI1c2FlbGFaU1dm
            MVo5Slh3M1V3MDVwZFNkeWVmRFdlQU0KpwaW3JMEqqmC5nBSofZUbXfHyP5dSHnf
            xXm4cp3OOhbgm7R8gzNwJOdh80eIi95QQPjWVOx/Nzh4OiJjf6Hrig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T07:50:22Z"
    mac: ENC[AES256_GCM,data:ERkVKA4XJO1HMERkFQLNuWNzgQ9C2vDua38VA23vN/dOZ/MM+AHBnGDExqv9KEhKZHbfA7ADke1sRj/AaaTVAVmX8KCGtTT5Eh3vwNc4NSyFO6gQJg8wM3Xa05swadjCn7khlDlA+VSTQT9N4ttTf9Kec9+vRqC+Z69fXub+0CA=,iv:idv4/4gju7R9irooY58wMmx9zY5wpSAbBbGERpZOzVo=,tag:8mtYllNRnd7llP68s2kEFw==,type:str]
    encrypted_regex: hw_address
    version: 3.12.2
