kea_subnet4:
    - subnet: 192.168.110.0/24
      pool: 192.168.110.30 - 192.168.110.127
      routers: 192.168.110.1
      dns_servers: 192.168.10.231,192.168.10.232
      domain_name: home.butaco.net
      reservations:
        - hw_address: ENC[AES256_GCM,data:/KLeSqWr7/1t+CUyuw8ZjlU=,iv:1sl+AIsxvV1Blgqg8pAY8IazAL9Tiy3odvOi9ZOOmUM=,tag:57LdArDdgqkVmvTRU4DV7w==,type:str]
          ip_address: 192.168.110.11
        - hw_address: ENC[AES256_GCM,data:vYrdpuMpf8fnHCX0giv0964=,iv:RC5V/IOcrFW91CB87QsWdLTQKG6n3MeruPcrpR2aHTc=,tag:UHV1URl2ed+XFZIHrWu5uQ==,type:str]
          ip_address: 192.168.110.12
        - hw_address: ENC[AES256_GCM,data:G3aSVMfOiqFbSDEFiBrsZGw=,iv:WmnXYkyIcWMhOCg10A09lldSCeYFJ8xQh4/6QlTCqmI=,tag:QE29vdK1vA961hEOljwrcA==,type:str]
          ip_address: 192.168.110.13
        - hw_address: ENC[AES256_GCM,data:6KNHIdKIcOX+4lES1Ww5eBw=,iv:SUi16OI+xpe4R3NPycZlcY1WnQa5njeBWFmNjnc7oLc=,tag:K4366mVXcFH1qyOTPtyddQ==,type:str]
          ip_address: 192.168.110.14
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV2pEaDdHMkZ6Y2pidnVo
            N3BtbVFxUXJLVzBXaytTY0VPTWlaSFo3a2hRCkxjOUw3b3lTaUJTRWxkRW9LSm9U
            TG5nc0VNVnVTUEVSazRzOHZpTlMzQ0kKLS0tIFlUSng3RlZ3QlI1c2FlbGFaU1dm
            MVo5Slh3M1V3MDVwZFNkeWVmRFdlQU0KpwaW3JMEqqmC5nBSofZUbXfHyP5dSHnf
            xXm4cp3OOhbgm7R8gzNwJOdh80eIi95QQPjWVOx/Nzh4OiJjf6Hrig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
    encrypted_regex: hw_address
    lastmodified: "2026-07-04T15:59:15Z"
    mac: ENC[AES256_GCM,data:YXICKtaaGIi/lQTn+YP3ZOwWmWSBg28k+eB7S7Psg/vhTI3MXxXv0EdS1Ok8ogWQMoLiHaFL3pcA8V6RCrG0IPyjxTQxKgm2jADE3oisnqQ+9C9hRtQTnGY2dsqi+ismv0htrpeKvOIWYdalou1la71pfptzRjmr+hTflo90ZVs=,iv:jn5kOWvAYrJ1mf83pW/aaZ6x0VVC9EijP2EMH4kKkRY=,tag:S6Foflm4JqmcNTkW/Sba9A==,type:str]
    version: 3.13.2
