kea_subnet4:
    - subnet: 192.168.110.0/24
      pool: 192.168.110.30 - 192.168.110.127
      routers: 192.168.110.1
      dns_servers: 192.168.10.231,192.168.10.232
      domain_name: home.butaco.net
      reservations:
        - hw_address: ENC[AES256_GCM,data:/KLeSqWr7/1t+CUyuw8ZjlU=,iv:1sl+AIsxvV1Blgqg8pAY8IazAL9Tiy3odvOi9ZOOmUM=,tag:57LdArDdgqkVmvTRU4DV7w==,type:str]
          ip_address: 192.168.110.11
        - hw_address: ENC[AES256_GCM,data:vYrdpuMpf8fnHCX0giv0964=,iv:RC5V/IOcrFW91CB87QsWdLTQKG6n3MeruPcrpR2aHTc=,tag:UHV1URl2ed+XFZIHrWu5uQ==,type:str]
          ip_address: 192.168.110.12
        - hw_address: ENC[AES256_GCM,data:G3aSVMfOiqFbSDEFiBrsZGw=,iv:WmnXYkyIcWMhOCg10A09lldSCeYFJ8xQh4/6QlTCqmI=,tag:QE29vdK1vA961hEOljwrcA==,type:str]
          ip_address: 192.168.110.13
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV2pEaDdHMkZ6Y2pidnVo
            N3BtbVFxUXJLVzBXaytTY0VPTWlaSFo3a2hRCkxjOUw3b3lTaUJTRWxkRW9LSm9U
            TG5nc0VNVnVTUEVSazRzOHZpTlMzQ0kKLS0tIFlUSng3RlZ3QlI1c2FlbGFaU1dm
            MVo5Slh3M1V3MDVwZFNkeWVmRFdlQU0KpwaW3JMEqqmC5nBSofZUbXfHyP5dSHnf
            xXm4cp3OOhbgm7R8gzNwJOdh80eIi95QQPjWVOx/Nzh4OiJjf6Hrig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T08:42:40Z"
    mac: ENC[AES256_GCM,data:gO43r2BBh0PtPOkADJqwWHikr8o/PgpbY+RsYXcFGeDyOUVSeo3I5V95f5nrMg4WghtmCHjY8xqOKt7259AZPiMGf8HkIckecWAmRw5/DHyHvEst/eTCzN6eMVSCgwnaMi3kxW+kizVZW5qr2l55NIBlhMs8gs78PSrzPCIFHqw=,iv:uI5ka3J581Pqlqjj6Fl0zvxU7iuCTj/WHQ+We1BTNs4=,tag:YnsKq8Q1pbJmAZZS0e7NlQ==,type:str]
    encrypted_regex: hw_address
    version: 3.12.2
