---
primary_auth_server: "{{ hostvars['ns1']['ansible_host'] }}:53"

secondary_auth_servers:
  - name: ns2
    address: "{{ hostvars['ns2']['ansible_host'] }}:53"
  - name: ns3
    address: "{{ hostvars['ns3']['ansible_host'] }}:53"

dns_resolver_servers:
  - name: resolver1
    address: "{{ hostvars['resolver1']['ansible_host'] }}:53"
  - name: resolver2
    address: "{{ hostvars['resolver2']['ansible_host'] }}:53"
