---
# Temporarily disabled due to expired certificate on repo.powerdns.com
pdns_repo_validate_certs: false

pdns_primary_addr: "{{ primary_auth_server.split(':')[0] }}"
pdns_primary_port: "{{ primary_auth_server.split(':')[1] }}"
pdns_primary_nameserver: "ns2.home.butaco.net"

pdns_webserver_port: 8081
pdns_webserver_allow_from: "192.168.10.0/24,192.168.20.0/24,192.168.30.0/24"

vector_config:
  sources:
    journald:
      type: journald
      include_units:
        - pdns
        - ssh
  transforms:
    parse_journald:
      type: remap
      inputs:
        - journald
      source: |
        .host = get_hostname!()
        .unit = string(.SYSTEMD_UNIT) ?? "unknown"
  sinks:
    loki:
      type: loki
      inputs:
        - parse_journald
      endpoint: "{{ loki_endpoint }}"
      encoding:
        codec: json
      healthcheck:
        enabled: false
      labels:
        host: !unsafe "{{ host }}"
        unit: !unsafe "{{ unit }}"
