---
dnsdist_default_servers:
  - name: local-forwarder
    address: "192.168.10.1:53"
    checkName: "google.com."
  - name: google-dns
    address: "8.8.8.8:53"
    checkName: "google.com."
  - name: cloudflare-dns
    address: "1.1.1.1:53"
    checkName: "cloudflare.com."

vector_config:
  sources:
    journald:
      type: journald
      include_units:
        - dnsdist
        - dnscollector
        - ssh
  transforms:
    parse_journald:
      type: remap
      inputs:
        - journald
      source: |
        .host = get_hostname!()
        .unit = string(._SYSTEMD_UNIT) ?? string(.SYSLOG_IDENTIFIER) ?? "unknown"
  sinks:
    loki:
      type: loki
      inputs:
        - parse_journald
      endpoint: "{{ loki_endpoint }}"
      encoding:
        codec: json
      healthcheck:
        enabled: false
      dangerously_allow_unconfined_template_resolution: true
      labels:
        host: !unsafe "{{ host }}"
        unit: !unsafe "{{ unit }}"
