---
openbao_tls_disable: true
openbao_api_addr: "https://openbao.home.butaco.net"

# Raft retry_join: empty for single-node, add other nodes when expanding to 3-node cluster
# openbao_raft_retry_join:
#   - "https://192.168.40.31:8200"
#   - "https://192.168.40.32:8200"
openbao_raft_retry_join: []

openbao_k8s_host: "https://192.168.30.11:6443"
openbao_k8s_dev_host: "https://192.168.20.11:6443"
