apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: searxng-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: {{ .Values.searxng.secret.key }}
        property: {{ .Values.searxng.secret.property }}
