proxmox:
  prd:
    username: ENC[AES256_GCM,data:bxvnkZjr+LOV7GmlC11zCNg=,iv:dJcoBi/LtkSi/LR+1nPXi32etsqMNAGilT6K+4VEV+0=,tag:UsOY0bgksvl7wijjSycuLg==,type:str]
    password: ENC[AES256_GCM,data:r5bCE52iuYuMpHmoYaLF9m4ow3N1Gu+eJJ3rLcf6hC0aKebm,iv:+yN7IaUQvSN5LeWiNvZ5akLZYQQ5Aeoh70nZlLIlleI=,tag:0hgD0LEOReB5pjdVZRsyqg==,type:str]
  dev:
    username: ENC[AES256_GCM,data:eD6BxrwIKPlXR1/oRz4jskc=,iv:pZHCTGLEMmTkcIhFjANkWM8AP3CVtjIIUQqNU2kobbU=,tag:aJay0Qwxm+hHlhppdjcbFQ==,type:str]
    password: ENC[AES256_GCM,data:LIb4muevlmX9TVAtD19gS/s50tKLueVgd8NUTNgf5cKJ5aVo,iv:MlUxyWG8tzcMsmlXMNlS/esbw/FMV6Ep0O9k1vYcTNs=,tag:GANGz7pvp35NBzju0nN5gw==,type:str]
  prd2:
    username: ENC[AES256_GCM,data:ZJ53m7vMdQWzvoy/mj9hxKI=,iv:7rlnLcYAq8NxbPzKB1BfOAJZrqRRCc8JLzsASShxuQE=,tag:3hGVtEEQFasxY8Vd+SBt1A==,type:str]
    password: ENC[AES256_GCM,data:Y/KcOMrvUPqNeB47CTsHG7MKPDJCWuYPbkOry2usBS1L9/OK,iv:/jv3HXbgG4kqduZf8nPJEhjZ8B+vI2B/6y02Wr0RXWU=,tag:vubJ5YrxbARZYe2VxMdyUQ==,type:str]
truenas:
  key: ENC[AES256_GCM,data:V4nT8UQWJV9wOk7pgn3+hpfaUkXVsijG7gLl7fHvGfH0DflN/SyA1xRR3lQiWMnmOhkPdX/kS31Wa4AfvU6K6l9e,iv:5BJ8Fx0WyGt4vVFtRokkx1BL+SqgrEnj0e3g1iASs6s=,tag:JZZ3w4VuYrYyqKkmOTdipg==,type:str]
grafana:
  password: ENC[AES256_GCM,data:8sD7sTknjIQWT6U=,iv:CqhXrQorV7mrmyOx0Jd1skMTcjWAKauUeVkMvM8AdWA=,tag:t5Jbzq8i3wtSzwYsL0uKaQ==,type:str]
sops:
  age:
    - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR0xSN1dSL2JscUoyZkpO
        bWdiZnRXQXRaL3pIeHRKZGJQSzdQTUwrdEZrCjIwQW9WME9PaVVEV0lkSm5lc3dN
        VjQ3ZTNyOC9MTFNJOGp2RFFwbUJUbFEKLS0tIEhOd25hNGtWT211K0VIdXd5eGJv
        NTB2NzczdklrZEo5bjQvUTgzSi9JeUUKMTtsQG7opo4WIbj90t5C3zm/JMMBPv1X
        82/bYc3u0vV8MX4qmqhoRQuxFDGgDiaWhUYxbfM5UjeXTW9FNn/1Rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T14:14:17Z"
  mac: ENC[AES256_GCM,data:1MndDotHRzmFGktgRmyjyNHWDEBsj5eCNav3vrUa18nIACRQ6idSXX6melLI3c49oxAc24gv5pkvaWpn1XjFeQTKcU2BUI8VgRfJqbkdNkyAldep4YbI841I/YBXDr5fXU61y/vh6UuEeqjP8ahmD2HUH9zvjZCwOWVyk94VaPk=,iv:K0BIOzI0eivKQuIEUNr/rIsT5GxE0srgkc9y4lUsd6Q=,tag:mi6pizzbSwpeYBp8yJ7tpw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
