apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: {{ .Values.namespace }}
  labels:
    app: homepage
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: homepage-sa
      containers:
      - name: homepage
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "*"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        secret:
          secretName: homepage-config
