apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_PROXMOX_PRD_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: prd-token
    - secretKey: HOMEPAGE_VAR_PROXMOX_PRD_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: prd-secret
    - secretKey: HOMEPAGE_VAR_PROXMOX_DEV_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: dev-token
    - secretKey: HOMEPAGE_VAR_PROXMOX_DEV_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: dev-secret
    - secretKey: HOMEPAGE_VAR_PROXMOX_NODE2_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: node2-token
    - secretKey: HOMEPAGE_VAR_PROXMOX_NODE2_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: node2-secret
    - secretKey: HOMEPAGE_VAR_PROXMOX_NODE3_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: node3-token
    - secretKey: HOMEPAGE_VAR_PROXMOX_NODE3_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: node3-secret
    - secretKey: HOMEPAGE_VAR_PROXMOX_NODE4_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: node4-token
    - secretKey: HOMEPAGE_VAR_PROXMOX_NODE4_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/proxmox
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: node4-secret
    - secretKey: HOMEPAGE_VAR_TRUENAS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/truenas
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: key
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/homepage/grafana
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
