apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_PROXMOX_PRD_TOKEN
      remoteRef:
        key: k8s/homepage/proxmox
        property: prd-token
    - secretKey: HOMEPAGE_VAR_PROXMOX_PRD_SECRET
      remoteRef:
        key: k8s/homepage/proxmox
        property: prd-secret
    - secretKey: HOMEPAGE_VAR_PROXMOX_DEV_TOKEN
      remoteRef:
        key: k8s/homepage/proxmox
        property: dev-token
    - secretKey: HOMEPAGE_VAR_PROXMOX_DEV_SECRET
      remoteRef:
        key: k8s/homepage/proxmox
        property: dev-secret
    - secretKey: HOMEPAGE_VAR_PROXMOX_PRD2_TOKEN
      remoteRef:
        key: k8s/homepage/proxmox
        property: prd2-token
    - secretKey: HOMEPAGE_VAR_PROXMOX_PRD2_SECRET
      remoteRef:
        key: k8s/homepage/proxmox
        property: prd2-secret
    - secretKey: HOMEPAGE_VAR_TRUENAS_KEY
      remoteRef:
        key: k8s/homepage/truenas
        property: key
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        key: k8s/homepage/grafana
        property: password
