apiVersion: v1
kind: Secret
metadata:
  name: homepage-config
  namespace: {{ .Values.namespace }}
stringData:
  settings.yaml: |
{{ include "homepage.config.settings" . | indent 4 }}
  services.yaml: |
{{ include "homepage.config.services" . | indent 4 }}
  proxmox.yaml: |
{{ include "homepage.config.proxmox" . | indent 4 }}
  widgets.yaml: |
{{ include "homepage.config.widgets" . | indent 4 }}
  bookmarks.yaml: |
    ---
    # https://gethomepage.dev/latest/configs/bookmarks/
  kubernetes.yaml: |
    mode: default
    ingress: false
  docker.yaml: ""
  custom.css: ""
  custom.js: ""
