apiVersion: v1
kind: Secret
metadata:
  name: homepage-config
  namespace: {{ .Values.namespace }}
stringData:
  {{- range $path, $_ :=  .Files.Glob "config/*.yaml" }}
  {{ base $path }}: |-
{{ tpl ($.Files.Get $path) $ | indent 4 }}
  {{- end }}
  docker.yaml: ""
  custom.css: ""
  custom.js: ""
