apiVersion: v1
kind: Service
metadata:
  name: homepage-lb
  namespace: {{ .Values.namespace }}
  labels:
    app: homepage
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: homepage
