---
- name: reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart seaweedfs
  become: true
  ansible.builtin.service:
    name: seaweedfs
    state: restarted

- name: restart seaweedfs-admin
  become: true
  ansible.builtin.service:
    name: seaweedfs-admin
    state: restarted
