---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart seaweedfs
  become: true
  ansible.builtin.service:
    name: seaweedfs
    state: restarted

- name: Restart seaweedfs-admin
  become: true
  ansible.builtin.service:
    name: seaweedfs-admin
    state: restarted
