apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-dev-kubeconfig
  namespace: headlamp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: headlamp-dev-kubeconfig
    creationPolicy: Owner
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: kubeconfig/dev
        property: kubeconfig
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-prd-kubeconfig
  namespace: headlamp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: headlamp-prd-kubeconfig
    creationPolicy: Owner
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: kubeconfig/prd
        property: kubeconfig
