forgejo:
    gitea:
        admin:
            username: ENC[AES256_GCM,data:n2CyQgf3QlU=,iv:vAC4aT1DFOqbwqyOxylJe+NB6hbxxtOKTO9BfrNBg9s=,tag:Ojupma0c0L+mqwgZvK2aVg==,type:str]
            password: ENC[AES256_GCM,data:DGrQ2WCSIKt55Sw=,iv:fZZDlquCPXHtIqWnhHupsnu5VZt8r+HGBNXgxFS0LtI=,tag:3NlYaYK0PtZOe9Wu4ljjZg==,type:str]
            email: ENC[AES256_GCM,data:oIpvfC25JLz10EeTNvIezQ==,iv:E3A+N4aCrBt/l2Oe9hD4hL7FrdFgWZjH+Z2QMdPWiO4=,tag:wPtkyEZ4AZjC9haQDFD8XQ==,type:str]
sops:
    age:
        - recipient: age1decj2rmd02e04jyuytn32wh6vay0v0hptm5m9qwqpcaw6fcwxyqscc403v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLejMwd2NBdHhvTE82RmhU
            WmtIcnBHYmxtMmlpby90VCszQjhodjd1Mno4CkRZOVFUbU81T3k2SFVxYzZrS2hu
            TGNaK2szS25reGVjdXBaeVFLN0VEeDQKLS0tIHduSWgvQzlnRVJ4alpRNElJaGhk
            UDBHR1FkM21tekxRVHFqcHFpQjRqMnMKgO6MqZWMdTg4vZNqrIQhEHtT7vRerGpy
            yRjfCuQO8QHzJkk7QXp3PU6+P7h6qVplzuBFz+CSYWsCxK6n+JA+IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T10:00:09Z"
    mac: ENC[AES256_GCM,data:zRPQnG2OhWP9JW0K3B3dPLb8STbOjPKWAiQT2u4OIUUmrfMZF8rwGUZATp9ICaHgj6zIpTuCMrx+ySVWaD4djXOCBsfhuP0PdRTxRf3Y3nHfSKYmYPhnO5QRrpC5fCi/2rdieXIxFRLFnVDydR/Fgry1CyZHGGObMiNx/edSVi0=,iv:Mhvox26dp+hL6ZRLsO3e32Y0lNgBuTvIVhGFXfLBgLo=,tag:8vcKHdsHV+Hyf4j4/6vXeg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
