---
# https://gethomepage.dev/latest/configs/bookmarks/

- Homepage:
  - Homepage:
    - abbrev: HP
    - href: https://gethomepage.dev/

  - Dashboard Icons:
    - abbrev: DI
    - href: https://github.com/homarr-labs/dashboard-icons

  - Material Design Icons:
    - abbrev: MD
    - href: https://pictogrammers.com/library/mdi/

  - Simple Icons:
    - abbrev: SI
    - href: https://simpleicons.org/

  - Selfhst Icons:
    - abbrev: SE
    - href: https://selfh.st/icons/
