{{- range $key, $val := .Values.proxmox }}
{{- if and $val.node $val.url }}
{{ $val.node }}:
  url: {{ $val.url }}
  token: {{ "{{" }}PROXMOX_{{ $key | upper }}_TOKEN{{ "}}" }}
  secret: {{ "{{" }}PROXMOX_{{ $key | upper }}_SECRET{{ "}}" }}
{{- end }}
{{- end }}
