{{- range .Values.proxmox }}
{{- if and $val.node $val.url }}
{{ $val.node }}:
  url: {{ $val.url }}
  token: {{ "{{" }}HOMEPAGE_VAR_PROXMOX_{{ $key | upper }}_TOKEN{{ "}}" }}
  secret: {{ "{{" }}HOMEPAGE_VAR_PROXMOX_{{ $key | upper }}_SECRET{{ "}}" }}
{{- end }}
{{- end }}
