---
# https://gethomepage.dev/latest/configs/services/

- DNS:
    - Authoritative:
        - PowerDNS auth1:
            icon: powerdns.png
            href: {{ .Values.pdns.primary.url }}
            description: Primary Authoritative DNS ({{ .Values.pdns.primary.addr }}:1053)
            proxmoxNode: {{ .Values.pdns.primary.pveNode }}
            proxmoxVMID: {{ .Values.pdns.primary.pveVmid }}
            proxmoxType: {{ .Values.pdns.primary.pveType }}
            siteMonitor: http://{{ .Values.pdns.primary.addr }}:8081/

        - PowerDNS auth2:
            icon: powerdns.png
            href: {{ .Values.pdns.secondary.url }}
            description: Secondary Authoritative DNS ({{ .Values.pdns.secondary.addr }}:1053)
            siteMonitor: http://{{ .Values.pdns.secondary.addr }}:8081/

    - DNS Balancer:
        - dnsdist1:
            icon: mdi-dns
            href: {{ .Values.dnsdist.dnsdist1.url }}
            description: DNS Load Balancer ({{ .Values.dnsdist.dnsdist1.addr }}:53)
            proxmoxNode: {{ .Values.dnsdist.dnsdist1.pveNode }}
            proxmoxVMID: {{ .Values.dnsdist.dnsdist1.pveVmid }}
            proxmoxType: {{ .Values.dnsdist.dnsdist1.pveType }}
            siteMonitor: http://{{ .Values.dnsdist.dnsdist1.addr }}:8083/

        - dnsdist2:
            icon: mdi-dns
            href: {{ .Values.dnsdist.dnsdist2.url }}
            description: DNS Load Balancer ({{ .Values.dnsdist.dnsdist2.addr }}:53)
            siteMonitor: http://{{ .Values.dnsdist.dnsdist2.addr }}:8083/

- HyperVisor:
    {{- range $key, $val := .Values.proxmox }}
    {{- if and $val.node $val.url }}
    - Proxmox VE {{ $key | title }}:
        icon: proxmox.png
        href: {{ $val.url }}
        description: Virtualization Platform
        widget:
          type: proxmox
          url: {{ $val.url }}
          username: {{ $val.token }}
          password: {{ $val.secret }}
          node: {{ $val.node }}
    {{- end }}
    {{- end }}

- Storage:
    - TrueNAS:
        icon: truenas.png
        href: {{ .Values.truenas.url }}
        description: Network Storage
        proxmoxNode: {{ .Values.truenas.pveNode }}
        proxmoxVMID: {{ .Values.truenas.pveVmid }}
        widget:
          type: truenas
          url: {{ .Values.truenas.url }}
          key: {{ .Values.truenas.key }}
          nasType: scale

- IPAM:
    - NetBox:
        icon: netbox.png
        href: {{ .Values.netbox.url }}
        description: IP Management
        proxmoxNode: {{ .Values.netbox.pveNode }}
        proxmoxVMID: {{ .Values.netbox.pveVmid }}
        proxmoxType: {{ .Values.netbox.pveType }}

- Monitoring:
    - Grafana:
        icon: grafana.png
        href: {{ .Values.grafana.url }}
        description: Metrics Visualization
        widget:
          type: grafana
          version: 2
          url: {{ .Values.grafana.url }}
          username: {{ .Values.grafana.username }}
          password: {{ .Values.grafana.password }}

    - Prometheus:
        icon: prometheus.png
        href: {{ .Values.prometheus.url }}
        description: Monitoring System
        widget:
          type: prometheus
          url: {{ .Values.prometheus.url }}

- Develop:
    - forgejo:
        icon: forgejo.png
        href: {{ .Values.forgejo.url }}
        description: Git Repository

- CD:
    - ArgoCD(Prod):
        icon: argo-cd.png
        href: {{ .Values.prdArgo.url }}
        description: Continuous Delivery

    - ArgoCD(Dev):
        icon: argo-cd.png
        href: {{ .Values.devArgo.url }}
        description: Continuous Delivery

- Application:
    - Open WebUI:
        icon: open-webui.png
        href: {{ .Values.openWebui.url }}
        description: Local LLM WebUI

    - ComfyUI:
        icon: comfyui.png
        href: {{ .Values.comfyUI.url }}
        description: ComfyUI

- Remote Management:
    - MeshCentral:
        icon: si-intel-#0071C5
        href: {{ .Values.meshCentral.url }}
        description: MeshCentral AMT remote control

- Network Element:
    - bgw1:
        icon: mdi-router
        description: Border Gateway ({{ .Values.network.bgw1 }})

    - C1200:
        icon: mdi-switch
        href: http://{{ .Values.network.c1200 }}/
        description: L3-SW ({{ .Values.network.c1200 }})

    - WiFi-AP1:
        icon: mdi-access-point-network
        href: http://{{ .Values.network.wifiAp1 }}/
        description: wifi-ap1

    - WiFi-AP2:
        icon: mdi-access-point-network
        href: http://{{ .Values.network.wifiAp2 }}/
        description: wifi-ap2
