---
# https://gethomepage.dev/latest/configs/services/

- Hypervisor:
    {{- range .Values.proxmox }}
    {{- if and .node .url }}
    - Proxmox VE {{ .key | title }}:
        icon: proxmox.png
        href: {{ .url }}
        description: Virtualization Platform
        widget:
          type: proxmox
          url: {{ .url }}
          username: {{ "{{" }}HOMEPAGE_VAR_PROXMOX_{{ .key | upper }}_TOKEN{{ "}}" }}
          password: {{ "{{" }}HOMEPAGE_VAR_PROXMOX_{{ .key | upper }}_SECRET{{ "}}" }}
          node: {{ .node }}
    {{- end }}
    {{- end }}

- Storage:
    - TrueNAS:
        icon: truenas.png
        href: {{ .Values.truenas.url }}
        description: Network Storage
        proxmoxNode: {{ .Values.truenas.pveNode }}
        proxmoxVMID: {{ .Values.truenas.pveVmid }}
        widget:
          type: truenas
          version: 2
          url: {{ .Values.truenas.url }}
          key: {{ "{{" }}HOMEPAGE_VAR_TRUENAS_KEY{{ "}}" }}
          nasType: scale

    - SeaweedFS:
        icon: sh-seaweedfs.png
        href: {{ .Values.seaweedfs.url }}
        description: Object Storage

    - OpenBAO:
        icon: openbao.png
        href: {{ .Values.openbao.url }}
        description: Secret Management
        proxmoxNode: {{ .Values.openbao.pveNode }}
        proxmoxVMID: {{ .Values.openbao.pveVmid }}

- DNS:
    - PowerDNS origin:
        icon: powerdns.png
        href: {{ .Values.pdns.primary.url }}
        description: Primary Authoritative DNS ({{ .Values.pdns.primary.addr }}:53)
        proxmoxNode: {{ .Values.pdns.primary.pveNode }}
        proxmoxVMID: {{ .Values.pdns.primary.pveVmid }}
        proxmoxType: {{ .Values.pdns.primary.pveType }}

    - PowerDNS auth1:
        icon: powerdns.png
        href: {{ .Values.pdns.secondary1.url }}
        description: Secondary1 Authoritative DNS ({{ .Values.pdns.secondary1.addr }}:53)
        proxmoxNode: {{ .Values.pdns.secondary1.pveNode }}
        proxmoxVMID: {{ .Values.pdns.secondary1.pveVmid }}
        proxmoxType: {{ .Values.pdns.secondary1.pveType }}

    - PowerDNS auth2:
        icon: powerdns.png
        href: {{ .Values.pdns.secondary2.url }}
        description: Secondary2 Authoritative DNS ({{ .Values.pdns.secondary2.addr }}:53)
        proxmoxNode: {{ .Values.pdns.secondary2.pveNode }}
        proxmoxVMID: {{ .Values.pdns.secondary2.pveVmid }}
        proxmoxType: {{ .Values.pdns.secondary2.pveType }}

    - dnsdist1:
        icon: mdi-dns
        href: {{ .Values.dnsdist.dnsdist1.url }}
        description: DNS Load Balancer ({{ .Values.dnsdist.dnsdist1.addr }}:53)
        proxmoxNode: {{ .Values.dnsdist.dnsdist1.pveNode }}
        proxmoxVMID: {{ .Values.dnsdist.dnsdist1.pveVmid }}
        proxmoxType: {{ .Values.dnsdist.dnsdist1.pveType }}

    - dnsdist2:
        icon: mdi-dns
        href: {{ .Values.dnsdist.dnsdist2.url }}
        description: DNS Load Balancer ({{ .Values.dnsdist.dnsdist2.addr }}:53)
        proxmoxNode: {{ .Values.dnsdist.dnsdist2.pveNode }}
        proxmoxVMID: {{ .Values.dnsdist.dnsdist2.pveVmid }}
        proxmoxType: {{ .Values.dnsdist.dnsdist2.pveType }}

- Infrastructure:
    - NetBox:
        icon: netbox.png
        href: {{ .Values.netbox.url }}
        description: IP Management
        proxmoxNode: {{ .Values.netbox.pveNode }}
        proxmoxVMID: {{ .Values.netbox.pveVmid }}
        proxmoxType: {{ .Values.netbox.pveType }}

- Monitoring:
    - Grafana:
        icon: grafana.png
        href: {{ .Values.grafana.url }}
        description: Metrics Visualization
        widget:
          type: grafana
          version: 2
          url: {{ .Values.grafana.url }}
          username: {{ .Values.grafana.username }}
          password: {{ "{{" }}HOMEPAGE_VAR_GRAFANA_PASSWORD{{ "}}" }}

    - Prometheus:
        icon: prometheus.png
        href: {{ .Values.prometheus.url }}
        description: Monitoring System
        widget:
          type: prometheus
          url: {{ .Values.prometheus.url }}

- Development:
    - Forgejo:
        icon: forgejo.png
        href: {{ .Values.forgejo.url }}
        description: Git Repository

    - Headlamp:
        icon: headlamp.png
        href: {{ .Values.headlamp.url }}
        description: k8s Cluster UI

- CI/CD:
    - ArgoCD (Prod):
        icon: argo-cd.png
        href: {{ .Values.prdArgo.url }}
        description: Continuous Delivery (prd)

    - ArgoCD (Dev):
        icon: argo-cd.png
        href: {{ .Values.devArgo.url }}
        description: Continuous Delivery (dev)

    - ArgoCD (Sandbox):
        icon: argo-cd.png
        href: {{ .Values.sandboxArgo.url }}
        description: Continuous Delivery (sandbox)

- AI:
    - Open WebUI:
        icon: open-webui.png
        href: {{ .Values.openWebui.url }}
        description: Local LLM WebUI

    - Lemonade Server:
        icon: sh-lemonade-ai
        href: {{ .Values.lemonadeServer.url }}
        description: Local LLM Inference Server

    - ComfyUI:
        icon: comfyui.png
        href: {{ .Values.comfyUI.url }}
        description: Image Generation UI

- Remote Management:
    - MeshCentral:
        icon: si-intel-#0071C5
        href: {{ .Values.meshCentral.url }}
        description: MeshCentral AMT remote control

- Network:
    - bgw1:
        icon: mdi-router
        description: Border Gateway ({{ .Values.network.bgw1 }})

    - C1200:
        icon: mdi-switch
        href: http://{{ .Values.network.c1200 }}/
        description: L3-SW ({{ .Values.network.c1200 }})

    - WiFi-AP1:
        icon: mdi-access-point-network
        href: http://{{ .Values.network.wifiAp1 }}/
        description: wifi-ap1
