---
# https://gethomepage.dev/latest/configs/services/

- Hypervisor:
    - Proxmox VE PVE:
        icon: proxmox.png
        href: https://pve.home.butaco.net:8006
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://pve.home.butaco.net:8006
          username: "{{HOMEPAGE_VAR_PROXMOX_PVE_TOKEN}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_PVE_SECRET}}"
          node: pve

    - Proxmox VE Node1:
        icon: proxmox.png
        href: https://node1.home.butaco.net:8006
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node1.home.butaco.net:8006
          username: "{{HOMEPAGE_VAR_PROXMOX_NODE1_TOKEN}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_NODE1_SECRET}}"
          node: node1

    - Proxmox VE Node2:
        icon: proxmox.png
        href: https://node2.home.butaco.net:8006
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node2.home.butaco.net:8006
          username: "{{HOMEPAGE_VAR_PROXMOX_NODE2_TOKEN}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_NODE2_SECRET}}"
          node: node2

    - Proxmox VE Node3:
        icon: proxmox.png
        href: https://node3.home.butaco.net:8006
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node3.home.butaco.net:8006
          username: "{{HOMEPAGE_VAR_PROXMOX_NODE3_TOKEN}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_NODE3_SECRET}}"
          node: node3

    - Proxmox VE Node4:
        icon: proxmox.png
        href: https://node4.home.butaco.net:8006
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node4.home.butaco.net:8006
          username: "{{HOMEPAGE_VAR_PROXMOX_NODE4_TOKEN}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_NODE4_SECRET}}"
          node: node4

    - Proxmox VE Node5:
        icon: proxmox.png
        href: https://node5.home.butaco.net:8006
        description: Virtualization Platform
        widget:
          type: proxmox
          url: https://node5.home.butaco.net:8006
          username: "{{HOMEPAGE_VAR_PROXMOX_NODE5_TOKEN}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_NODE5_SECRET}}"
          node: node5

- Storage:
    - TrueNAS:
        icon: truenas.png
        href: https://truenas-ui.home.butaco.net
        description: Network Storage
        proxmoxNode: node1
        proxmoxVMID: "100"
        proxmoxType: qemu
        widget:
          type: truenas
          version: 2
          url: https://truenas-ui.home.butaco.net
          key: "{{HOMEPAGE_VAR_TRUENAS_KEY}}"
          nasType: scale

    - SeaweedFS:
        icon: sh-seaweedfs.png
        href: https://seaweedfs-ui.home.butaco.net
        description: Object Storage
        proxmoxNode: node3
        proxmoxVMID: "103"
        proxmoxType: lxc

    - OpenBAO:
        icon: openbao.png
        href: https://openbao.home.butaco.net/
        description: Secret Management
        proxmoxNode: node2
        proxmoxVMID: "100"
        proxmoxType: qemu

- DNS:
    - PowerDNS origin:
        icon: powerdns.png
        href: https://pdns1.home.butaco.net
        description: Primary Authoritative DNS (ns1.home.butaco.net:53)
        proxmoxNode: node2
        proxmoxVMID: "108"
        proxmoxType: lxc

    - PowerDNS auth1:
        icon: powerdns.png
        href: https://pdns2.home.butaco.net
        description: Secondary1 Authoritative DNS (ns2.home.butaco.net:53)
        proxmoxNode: node3
        proxmoxVMID: "100"
        proxmoxType: lxc

    - PowerDNS auth2:
        icon: powerdns.png
        href: https://pdns3.home.butaco.net
        description: Secondary2 Authoritative DNS (ns3.home.butaco.net:53)
        proxmoxNode: node2
        proxmoxVMID: "109"
        proxmoxType: lxc

    - dnsdist1:
        icon: mdi-dns
        href: https://dnsdist1.home.butaco.net
        description: DNS Load Balancer (dist1.home.butaco.net:53)
        proxmoxNode: node2
        proxmoxVMID: "107"
        proxmoxType: lxc

    - dnsdist2:
        icon: mdi-dns
        href: https://dnsdist2.home.butaco.net
        description: DNS Load Balancer (dist2.home.butaco.net:53)
        proxmoxNode: node3
        proxmoxVMID: "101"
        proxmoxType: lxc

- Infrastructure:
    - NetBox:
        icon: netbox.png
        href: https://netbox-ui.home.butaco.net
        description: IP Management
        proxmoxNode: node2
        proxmoxVMID: "106"
        proxmoxType: lxc

- Monitoring:
    - Grafana:
        icon: grafana.png
        href: https://grafana.prd.butaco.net
        description: Metrics Visualization
        widget:
          type: grafana
          version: 2
          url: https://grafana.prd.butaco.net
          username: admin
          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.prd.butaco.net
        description: Monitoring System
        widget:
          type: prometheus
          url: https://prometheus.prd.butaco.net

- Development:
    - Forgejo:
        icon: forgejo.png
        href: https://forgejo.home.butaco.net
        description: Git Repository
        proxmoxNode: node2
        proxmoxVMID: "103"
        proxmoxType: lxc

    - Headlamp:
        icon: headlamp.png
        href: https://headlamp.prd.butaco.net
        description: k8s Cluster UI

- CI/CD:
    - ArgoCD (Prod):
        icon: argo-cd.png
        href: https://argocd-ui.prd.butaco.net
        description: Continuous Delivery (prd)

    - ArgoCD (Sandbox):
        icon: argo-cd.png
        href: http://argocd.sandbox.butaco.net
        description: Continuous Delivery (sandbox)

- AI:
    - Open WebUI:
        icon: open-webui.png
        href: https://open-webui.prd.butaco.net
        description: Local LLM WebUI

    - Lemonade Server:
        icon: sh-lemonade-ai
        href: https://lemonade.prd.butaco.net
        description: Local LLM Inference Server

    - ComfyUI:
        icon: comfyui.png
        href: https://comfyui.prd.butaco.net
        description: Image Generation UI

- Remote Management:
    - MeshCentral:
        icon: si-intel-#0071C5
        href: https://meshcentral.prd.butaco.net
        description: MeshCentral AMT remote control

- Network:
    - bgw1:
        icon: mdi-router
        description: Border Gateway (bgw1.home.butaco.net)

    - C1200:
        icon: mdi-switch
        href: http://c1200.home.butaco.net/
        description: L3-SW (c1200.home.butaco.net)

    - WiFi-AP1:
        icon: mdi-access-point-network
        href: http://wifiap1.home.butaco.net/
        description: wifi-ap1
