---
# https://gethomepage.dev/latest/configs/settings/
title: HomeLab Portal
description: Homelab Portal
logpath: stdout
disableCollapse: true
useEqualHeights: true

# Display order; keys must exactly match service groups.
layout:
  Hypervisor:
    style: row
    columns: 6
  Storage:
    style: row
    columns: 3
  DNS:
    style: row
    columns: 5
  Infrastructure:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 5
  Development:
    style: row
    columns: 4
  CI/CD:
    style: row
    columns: 4
  AI:
    style: row
    columns: 7
  Remote Management:
    style: row
    columns: 4
  Network:
    style: row
    columns: 3
