apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/takanao14/homelab.git
    targetRevision: HEAD
    path: k8s/externalDNS/chart
    helm:
      valueFiles:
        - ../values-common.yaml
        - ../dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dns-homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
