apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://helm.openwebui.com/
      chart: open-webui
      targetRevision: 15.2.0
      helm:
        values: |
          ollama:
            enabled: false
          ollamaUrls:
            - http://ollama.ollama.svc.cluster.local:11434
          pipelines:
            enabled: false
          enableOpenaiApi: true
          openaiBaseApiUrls:
            - http://lemonade-server.lemonade-server.svc.cluster.local:13305/v1
          openaiApiKeys:
            - "dummy"
          persistence:
            enabled: true
            size: 2Gi
          ingress:
            enabled: false
          route:
            enabled: true
            hostnames:
              - open-webui.dev.butaco.net
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: shared-gateway-envoy
                namespace: gateway-system
                sectionName: https
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
