apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.openwebui.com/
      chart: open-webui
      targetRevision: 13.3.1
      helm:
        values: |
          ollama:
            enabled: false
          ollamaUrls:
            - http://ollama.ollama.svc.cluster.local:11434
          persistence:
            enabled: true
            size: 2Gi
          ingress:
            enabled: false
          route:
            enabled: true
            hostnames:
              - open-webui.dev.butaco.net
            parentRefs:
              - name: shared-gateway
                namespace: gateway-system
                sectionName: https
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
