gateway:
  name: shared-gateway-envoy
  namespace: gateway-system
  proxyNamespace: envoy-gateway-system

servers:
  grafana:
    image: docker.io/grafana/mcp-grafana:1.6.2@sha256:7101042adc027c59bd26eb52bd59bc5e8f76c049fd1c20722f16186806f9d859
    command: /app/mcp-grafana
    hostname: ""
    upstream: http://grafana.monitoring.svc.cluster.local
    secretPath: k8s/mcp/grafana
    upstreamTokenEnv: GRAFANA_SERVICE_ACCOUNT_TOKEN
    callerTokenEnv: MCP_GRAFANA_SERVER_TOKEN
    args:
      - -t
      - streamable-http
      - --address
      - 0.0.0.0:8000
      - --disable-write
      - --enabled-tools
      - search,datasource,prometheus,loki,dashboard,navigation,alerting
      - --max-loki-log-limit
      - "20"
  netbox:
    image: docker.io/netboxlabs/netbox-mcp-server:1.2.1@sha256:eba97a5ce807a8a77d627d55f46a5fdc70799e84383224de8dba5436e3cac92d
    command: netbox-mcp-server
    hostname: ""
    upstream: https://netbox.home.butaco.net/
    secretPath: k8s/mcp/netbox
    upstreamTokenEnv: NETBOX_TOKEN
    callerTokenEnv: MCP_AUTH_TOKEN
    args:
      - --transport
      - http
      - --host
      - 0.0.0.0
      - --port
      - "8000"

netboxIP: ""
