controller:
  dnsConfig:
    options:
      - name: ndots
        value: "2"

repoServer:
  dnsConfig:
    options:
      - name: ndots
        value: "2"

applicationSet:
  dnsConfig:
    options:
      - name: ndots
        value: "2"

redis:
  dnsConfig:
    options:
      - name: ndots
        value: "2"

server:
  dnsConfig:
    options:
      - name: ndots
        value: "2"
  ingress:
    hostname: argocd-ui.prd.butaco.net
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: argocd.prd.butaco.net
    type: LoadBalancer
