apiVersion: v2
name: envoy-gateway-controller
description: Envoy Gateway controller wrapper
type: application
version: 0.1.0
dependencies:
  - name: gateway-helm
    version: 1.8.2
    repository: oci://docker.io/envoyproxy
