#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${HOME}/.env"

BAO_ADDR="${OPENBAO_ADDR:-https://bao.prd.butaco.net}"
export BAO_ADDR

if ! command -v bao &>/dev/null; then
  echo "Error: bao CLI not found" >&2
  exit 1
fi

BAO_USERNAME="${BAO_USERNAME:-homelab}"
read -rsp "OpenBao password for ${BAO_USERNAME}: " _bao_pass; echo
BAO_TOKEN=$(bao login -method=userpass username="${BAO_USERNAME}" password="${_bao_pass}" -token-only)
export BAO_TOKEN

echo "Fetching secrets from OpenBao..."

{
  echo "# Generated by getenv.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  bao kv get -format=json secret/provision/env \
    | jq -r '.data.data | to_entries[] | "\(.key)=\(.value)"'
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "Written to ${ENV_FILE}"
