#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${HOME}/.env"

BAO_ADDR="${OPENBAO_ADDR:-https://openbao.home.butaco.net}"
export BAO_ADDR

if ! command -v bao &>/dev/null; then
  echo "Error: bao CLI not found" >&2
  exit 1
fi

BAO_USERNAME="${BAO_USERNAME:-homelab}"
# Resolve password: env var > interactive prompt (TTY) > stdin (non-interactive)
if [[ -n "${BAO_PASSWORD:-}" ]]; then
  _bao_pass="$BAO_PASSWORD"
elif [[ -t 0 ]]; then
  read -rsp "OpenBao password for ${BAO_USERNAME}: " _bao_pass; echo
else
  read -r _bao_pass
fi
BAO_TOKEN=$(bao login -token-only -method=userpass username="${BAO_USERNAME}" password="${_bao_pass}")
export BAO_TOKEN

echo "Fetching secrets from OpenBao..."

secrets_json="$(bao kv get -format=json secret/provision/env)"
invalid_keys="$(jq -r '.data.data | keys[] | select(test("^[A-Za-z_][A-Za-z0-9_]*$") | not)' <<<"$secrets_json")"
if [[ -n "$invalid_keys" ]]; then
  echo "Error: OpenBao secret contains invalid shell variable names:" >&2
  echo "$invalid_keys" >&2
  exit 1
fi

tmp_file="$(mktemp "${ENV_FILE}.tmp.XXXXXX")"
cleanup() {
  rm -f "$tmp_file"
}
trap cleanup EXIT

{
  echo "# Generated by getenv.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  jq -r '.data.data | to_entries[] | "\(.key)=\(.value | tostring | @sh)"' <<<"$secrets_json"
} > "$tmp_file"

chmod 600 "$tmp_file"
mv "$tmp_file" "$ENV_FILE"
trap - EXIT
echo "Written to ${ENV_FILE}"
