hostname: ""

gateway:
  name: shared-gateway-envoy
  namespace: gateway-system
  sectionName: https
  graphTimeouts:
    request: ""
    backendRequest: ""

otlp:
  hostname: ""
  loadBalancerIP: ""
