hostname: ""

image:
  repository: ghcr.io/ylianst/meshcentral
  tag: 1.1.59-slim

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

persistence:
  data:
    size: 1Gi
  files:
    size: 10Gi
  backups:
    size: 5Gi
  web:
    size: 1Gi

dynamicConfig: true
