modules:
  nec_ix:
    walk:
      - naptCacheTable
      - IP-MIB::ipInDiscards
      - IP-MIB::ipOutDiscards
      - IP-MIB::ipOutNoRoutes
      - IP-MIB::ipReasmFails
      - IP-MIB::ipFragFails
      - IP-MIB::ipFragCreates
      - IP-MIB::icmpOutDestUnreachs
      - UDP-MIB::udpNoPorts
      - UDP-MIB::udpInErrors
    lookups:
      - source_indexes: [naptCacheIfIndex]
        lookup: IF-MIB::ifDescr
      - source_indexes: [naptCacheIfIndex]
        lookup: IF-MIB::ifAlias
    overrides:
      naptCacheIfIndex:
        ignore: true
