apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pdns-ui-api
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: pdns-ui-api
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.secret.key }}
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: {{ .Values.secret.property }}
