apiVersion: v1
kind: Service
metadata:
  name: pdns-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: pdns-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: pdns-ui
