---
blackbox_exporter_port: 9115
blackbox_exporter_config_path: /etc/prometheus/blackbox.yml

# Internal domain to resolve for the DNS internal probe
blackbox_exporter_dns_internal_query: "ns1.home.butaco.net"
