apiVersion: v1
kind: Secret
metadata:
  name: external-dns-env
type: Opaque
stringData:
  PDNS_API_URL: {{ .Values.pdns.apiUrl | quote }}
  PDNS_SERVER_ID: {{ .Values.pdns.serverId | quote }}
  PDNS_HTTP_API_KEY: {{ .Values.pdns.apiKey | quote }}
  OWNER_ID_FOR_THIS_EXTERNAL_DNS: {{ .Values.ownerId | quote }}
  DOMAIN_FILTER: {{ .Values.domainFilter | quote }}
