---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - software-properties-common
    update_cache: true
  become: true

- name: Add kubernetes repository key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
  become: true

- name: Add kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /"
    filename: kubernetes
    state: present
  become: true

- name: Hold kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: Install kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true
  become: true

- name: Hold kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: Swap Off
  ansible.builtin.command:
    cmd: swapoff -a
  register: swapoff_result
  failed_when: swapoff_result.rc != 0
  changed_when: swapoff_result.rc == 0
  become: true

- name: Add kernel modules
  community.general.modprobe:
    name: br_netfilter
    persistent: present
    state: present
  become: true

- name: Set sysctl parameters
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - { key: net.ipv4.ip_forward, value: 1 }
  become: true
