#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/../lib/openbao-auth.sh"

ENV_FILE="${HOME}/.env"

BAO_ADDR="${OPENBAO_ADDR:-https://openbao.home.butaco.net}"
export BAO_ADDR

if ! command -v bao &>/dev/null; then
  echo "Error: bao CLI not found" >&2
  exit 1
fi

BAO_USERNAME="${BAO_USERNAME:-homelab}"
openbao_authenticate

echo "Fetching secrets from OpenBao..."

secrets_json="$(bao kv get -format=json secret/provision/env)"
invalid_keys="$(jq -r '.data.data | keys[] | select(test("^[A-Za-z_][A-Za-z0-9_]*$") | not)' <<<"$secrets_json")"
if [[ -n "$invalid_keys" ]]; then
  echo "Error: OpenBao secret contains invalid shell variable names:" >&2
  echo "$invalid_keys" >&2
  exit 1
fi

reserved_keys="$(
  jq -r '.data.data | keys[] | select(. == "BAO_TOKEN" or . == "BAO_PASSWORD")' <<<"$secrets_json"
)"
if [[ -n "$reserved_keys" ]]; then
  echo "Warning: skipping reserved OpenBao variables:" >&2
  echo "$reserved_keys" >&2
fi

unsafe_values="$(
  jq -r '
    .data.data
    | to_entries[]
    | select(.key != "BAO_TOKEN" and .key != "BAO_PASSWORD")
    | select((.value | tostring | test("\\$\\(|`")))
    | .key
  ' <<<"$secrets_json"
)"
if [[ -n "$unsafe_values" ]]; then
  echo "Error: OpenBao secret contains command substitutions:" >&2
  echo "$unsafe_values" >&2
  exit 1
fi

tmp_file="$(mktemp "${ENV_FILE}.tmp.XXXXXX")"
cleanup() {
  rm -f "$tmp_file"
}
trap cleanup EXIT

{
  echo "# Generated by getenv.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  jq -r '
    .data.data
    | to_entries[]
    | select(.key != "BAO_TOKEN" and .key != "BAO_PASSWORD")
    | .key + "=\"" + (.value | tostring | gsub("\\\\"; "\\\\") | gsub("\""; "\\\"")) + "\""
  ' <<<"$secrets_json"
} > "$tmp_file"

chmod 600 "$tmp_file"
mv "$tmp_file" "$ENV_FILE"
trap - EXIT
echo "Written to ${ENV_FILE}"
